/**
 * Generated by scripts/gen_monsters.py -- do not edit by hand.
 *
 * §9.5.8 -- what comes off a monster. Two Tier 1 families of five: a plate/hide
 * line the smith and the armorer want, an ichor/organ line the consumable bench
 * wants. Biome-free, because they come off a thing that walked there rather than
 * out of the ground, and dropped by nothing else.
 *
 * And a TIER 0 line of four, one per monster tier, dropped every time. §4's junk
 * argument applied to combat: the rubbish carried out alongside, worth a gold and
 * wanted by no recipe. It is generous precisely because it is worthless -- a drop
 * nobody can build with cannot inflate anything.
 *
 * Combat feeds combat. Nothing here enters the mining economy, which is what makes
 * a whole new faucet safe under §2.
 */
import type { Material } from './types'

export const SPOILS: Material[] = [
  { key: 'cracked_carapace', name: 'Cracked Carapace', tier: 1, palette: 'pelt', spoil: 'plate', grade: 1, npcPrice: 4, description: 'Comes off in sheets and takes a rivet without splitting. Most of it is waste.' },
  { key: 'bone_plate', name: 'Bone Plate', tier: 1, palette: 'pelt', spoil: 'plate', grade: 2, npcPrice: 7, description: 'Flat, dense, and already the right shape. The armorer barely has to cut.' },
  { key: 'scaled_hide', name: 'Scaled Hide', tier: 1, palette: 'pelt', spoil: 'plate', grade: 3, npcPrice: 11, description: 'Overlapped the whole way down. Turns a point that a flat hide would let through.' },
  { key: 'warped_barb', name: 'Warped Barb', tier: 1, palette: 'pelt', spoil: 'plate', grade: 4, npcPrice: 17, description: 'Grew wrong and hardened that way. Holds an edge nothing whetted can match.' },
  { key: 'revenant_plate', name: 'Revenant Plate', tier: 1, palette: 'pelt', spoil: 'plate', grade: 5, npcPrice: 26, description: 'Still warm. The smith works it fast, before it remembers what it was.' },
  { key: 'thin_ichor', name: 'Thin Ichor', tier: 1, palette: 'stone', spoil: 'ichor', grade: 1, npcPrice: 3, description: 'Runs like water and keeps for a week in a stoppered flask. Barely worth the flask.' },
  { key: 'black_blood', name: 'Black Blood', tier: 1, palette: 'stone', spoil: 'ichor', grade: 2, npcPrice: 6, description: 'Thick enough to draw a line with. The alchemist wants it for what it will not mix with.' },
  { key: 'bile_sac', name: 'Bile Sac', tier: 1, palette: 'stone', spoil: 'ichor', grade: 3, npcPrice: 10, description: 'Cut it out whole or lose the lot. Everything downstream of this is a nerve tonic.' },
  { key: 'ember_gland', name: 'Ember Gland', tier: 1, palette: 'stone', spoil: 'ichor', grade: 4, npcPrice: 16, description: 'Hot in the hand an hour after the thing stopped moving.' },
  { key: 'grave_heart', name: 'Grave Heart', tier: 1, palette: 'stone', spoil: 'ichor', grade: 5, npcPrice: 25, description: 'It beat once on the bench. Nobody who saw it wants to talk about it.' },
  { key: 'chipped_fang', name: 'Chipped Fang', tier: 0, palette: 'stone', grade: 1, npcPrice: 1, description: 'Snapped off in something harder than it was. Everybody on the rim has a jar of them.' },
  { key: 'cracked_horn', name: 'Cracked Horn', tier: 0, palette: 'stone', grade: 2, npcPrice: 1, description: 'Split down the middle and no use to anybody. It still smells of the thing.' },
  { key: 'snapped_quill', name: 'Snapped Quill', tier: 0, palette: 'stone', grade: 3, npcPrice: 1, description: 'Hollow, light, and sharp at the wrong end. Nothing will take it as a point.' },
  { key: 'charred_sinew', name: 'Charred Sinew', tier: 0, palette: 'stone', grade: 4, npcPrice: 1, description: 'Went through a fire before you got to it. It will not hold a knot.' },
]

export const SPOILS_BY_GRADE: Record<number, { plate: string; ichor: string }> = {
  1: { plate: 'cracked_carapace', ichor: 'thin_ichor' },
  2: { plate: 'bone_plate', ichor: 'black_blood' },
  3: { plate: 'scaled_hide', ichor: 'bile_sac' },
  4: { plate: 'warped_barb', ichor: 'ember_gland' },
  5: { plate: 'revenant_plate', ichor: 'grave_heart' },
}

/** §4 -- monster tier -> the tier-0 leaving it drops every time. */
export const TROPHY_BY_TIER: Record<number, string> = {
  1: 'chipped_fang',
  2: 'cracked_horn',
  3: 'snapped_quill',
  4: 'charred_sinew',
}
