/**
 * Generated by scripts/gen_monsters.py -- do not edit by hand.
 *
 * §9.5.8 -- what comes off a monster, in four lines.
 *
 * Two Tier 1 families of five say how hard the thing was: a plate/hide line the
 * smith and the armorer want, an ichor/organ line the consumable bench wants.
 * Those are graded by tier and are the same everywhere, because a tier-3 fight is
 * a tier-3 fight on any ground.
 *
 * A third Tier 1 line says WHERE it lived: one stock per biome, dropped only by
 * that country's five (§9.5.2). It is the one drop a prospector cannot get by
 * walking inward on ground they already know, which is what makes kitting out of a
 * country's line a reason to go and fight in that country.
 *
 * And TIER 0, in two lines of its own. The **trophy** is one per monster tier and
 * is dropped every time -- what you fought. The **leaving** is one per biome and is
 * a roll -- where the fight happened. §4's junk argument applied to combat: worth a
 * gold, wanted by no recipe, and generous precisely because it is worthless, since
 * a drop nobody can build with cannot inflate anything.
 *
 * *(The leaving used to be §4's own mining junk, borrowed. That was only ever a
 * borrow because a strap was scarce, and §7.6 made straps roomy -- so the fight
 * has its own rubbish now, and the mine keeps its.)*
 *
 * Combat feeds combat. Nothing here enters the mining economy, which is what makes
 * a whole new faucet safe under §2.
 */
import type { Material } from './types'

export const SPOILS: Material[] = [
  { key: 'cracked_carapace', name: 'Cracked Carapace', tier: 1, palette: 'pelt', spoil: 'plate', grade: 1, npcPrice: 4, description: 'Comes off in sheets and takes a rivet without splitting. Most of it is waste.' },
  { key: 'bone_plate', name: 'Bone Plate', tier: 1, palette: 'pelt', spoil: 'plate', grade: 2, npcPrice: 7, description: 'Flat, dense, and already the right shape. The armorer barely has to cut.' },
  { key: 'scaled_hide', name: 'Scaled Hide', tier: 1, palette: 'pelt', spoil: 'plate', grade: 3, npcPrice: 11, description: 'Overlapped the whole way down. Turns a point that a flat hide would let through.' },
  { key: 'warped_barb', name: 'Warped Barb', tier: 1, palette: 'pelt', spoil: 'plate', grade: 4, npcPrice: 17, description: 'Grew wrong and hardened that way. Holds an edge nothing whetted can match.' },
  { key: 'revenant_plate', name: 'Revenant Plate', tier: 1, palette: 'pelt', spoil: 'plate', grade: 5, npcPrice: 26, description: 'Still warm. The smith works it fast, before it remembers what it was.' },
  { key: 'thin_ichor', name: 'Thin Ichor', tier: 1, palette: 'stone', spoil: 'ichor', grade: 1, npcPrice: 3, description: 'Runs like water and keeps for a week in a stoppered flask. Barely worth the flask.' },
  { key: 'black_blood', name: 'Black Blood', tier: 1, palette: 'stone', spoil: 'ichor', grade: 2, npcPrice: 6, description: 'Thick enough to draw a line with. The alchemist wants it for what it will not mix with.' },
  { key: 'bile_sac', name: 'Bile Sac', tier: 1, palette: 'stone', spoil: 'ichor', grade: 3, npcPrice: 10, description: 'Cut it out whole or lose the lot. Everything downstream of this is a nerve tonic.' },
  { key: 'ember_gland', name: 'Ember Gland', tier: 1, palette: 'stone', spoil: 'ichor', grade: 4, npcPrice: 16, description: 'Hot in the hand an hour after the thing stopped moving.' },
  { key: 'grave_heart', name: 'Grave Heart', tier: 1, palette: 'stone', spoil: 'ichor', grade: 5, npcPrice: 25, description: 'It beat once on the bench. Nobody who saw it wants to talk about it.' },
  { key: 'chipped_fang', name: 'Chipped Fang', tier: 0, palette: 'stone', grade: 1, npcPrice: 1, description: 'Snapped off in something harder than it was. Everybody on the rim has a jar of them.' },
  { key: 'cracked_horn', name: 'Cracked Horn', tier: 0, palette: 'stone', grade: 2, npcPrice: 1, description: 'Split down the middle and no use to anybody. It still smells of the thing.' },
  { key: 'snapped_quill', name: 'Snapped Quill', tier: 0, palette: 'stone', grade: 3, npcPrice: 1, description: 'Hollow, light, and sharp at the wrong end. Nothing will take it as a point.' },
  { key: 'charred_sinew', name: 'Charred Sinew', tier: 0, palette: 'stone', grade: 4, npcPrice: 1, description: 'Went through a fire before you got to it. It will not hold a knot.' },
  { key: 'sap_matted_fur', name: 'Sap-Matted Fur', tier: 1, palette: 'pelt', spoil: 'biome', biome: 'forest', npcPrice: 8, description: 'Comes off the shoulders in one piece, and everything it touched is stuck to it.' },
  { key: 'ore_crusted_chitin', name: 'Ore-Crusted Chitin', tier: 1, palette: 'pelt', spoil: 'biome', biome: 'mountain', npcPrice: 8, description: 'It fed on the seam it slept in. Half the shell is the seam.' },
  { key: 'braided_sinew', name: 'Braided Sinew', tier: 1, palette: 'pelt', spoil: 'biome', biome: 'plains', npcPrice: 8, description: 'Laid down in cords by a thing that ran every day of its life. It will not part.' },
  { key: 'slagged_scale', name: 'Slagged Scale', tier: 1, palette: 'pelt', spoil: 'biome', biome: 'badlands', npcPrice: 8, description: 'Ran once and set again. Nothing the smith has will make it do that twice.' },
  { key: 'pollen_choked_gill', name: 'Pollen-Choked Gill', tier: 1, palette: 'pelt', spoil: 'biome', biome: 'grassland', npcPrice: 8, description: 'Packed solid with a summer of it. The alchemist takes the packing, not the gill.' },
  { key: 'trampled_fern', name: 'Trampled Fern', tier: 0, palette: 'stone', biome: 'forest', npcPrice: 1, description: 'Flattened in the scuffle and already browning. It was not worth much standing up.' },
  { key: 'shale_grit', name: 'Shale Grit', tier: 0, palette: 'stone', biome: 'mountain', npcPrice: 1, description: 'Came down off the slope while you were busy. It is in everything now.' },
  { key: 'matted_turf', name: 'Matted Turf', tier: 0, palette: 'stone', biome: 'plains', npcPrice: 1, description: 'Torn up by whatever was braced against it. Roots, dirt, and nothing else.' },
  { key: 'scorched_grit', name: 'Scorched Grit', tier: 0, palette: 'stone', biome: 'badlands', npcPrice: 1, description: 'Fused into little beads where something hot went over it.' },
  { key: 'broken_stalks', name: 'Broken Stalks', tier: 0, palette: 'stone', biome: 'grassland', npcPrice: 1, description: 'A double handful of what the fight went through. It will not even burn well.' },
]

export const SPOILS_BY_GRADE: Record<number, { plate: string; ichor: string }> = {
  1: { plate: 'cracked_carapace', ichor: 'thin_ichor' },
  2: { plate: 'bone_plate', ichor: 'black_blood' },
  3: { plate: 'scaled_hide', ichor: 'bile_sac' },
  4: { plate: 'warped_barb', ichor: 'ember_gland' },
  5: { plate: 'revenant_plate', ichor: 'grave_heart' },
}

/** §4 -- monster tier -> the tier-0 leaving it drops every time. */
export const TROPHY_BY_TIER: Record<number, string> = {
  1: 'chipped_fang',
  2: 'cracked_horn',
  3: 'snapped_quill',
  4: 'charred_sinew',
}

/** §9.5.8 -- biome -> the stock only that country's monsters give up. */
export const BIOME_SPOIL: Record<string, string> = {
  forest: 'sap_matted_fur',
  mountain: 'ore_crusted_chitin',
  plains: 'braided_sinew',
  badlands: 'slagged_scale',
  grassland: 'pollen_choked_gill',
}

/** §9.5.8 -- biome -> the tier-0 leaving that says where the fight was. */
export const BIOME_LEAVING: Record<string, string> = {
  forest: 'trampled_fern',
  mountain: 'shale_grit',
  plains: 'matted_turf',
  badlands: 'scorched_grit',
  grassland: 'broken_stalks',
}
