/**
 * Generated by scripts/gen_toptier.py -- do not edit by hand.
 *
 * §8.0 -- the two rungs above epic. Neither is reachable and both are defined, so
 * the whole six-rung ladder can be read off one page.
 *
 * Legendary needs a guild hall, and guild halls do not exist (§10). Unique has no
 * bench and no recipe at all: it drops, and it is soulbound the moment it lands,
 * because §2 forbids a grind-to-external-value faucet and a tradeable drop would
 * be exactly that. The `weapon` slot stays empty until raid combat is designed.
 */
import type { ItemDef } from './types'

export const TOP_TIER: ItemDef[] = [
  { key: 'grovefeller', name: 'Grovefeller', slot: 'axe', rarity: 'legendary', tradeable: true, stat: 'yield', value: 0.14, palette: 'wood', station: 'guild', maxDurability: 240, inputs: { ironwood: 5, heartoak: 10, bentwood: 6, heartknot: 6, reinforced_frame: 3, core: 1 }, description: 'Two hands and a full swing. The stand goes quiet around it.' },
  { key: 'the_last_bough', name: 'The Last Bough', slot: 'axe', rarity: 'unique', tradeable: false, stat: 'yield', value: 0.15, palette: 'wood', maxDurability: 260, perk: 'Reads the grade of every forest hex inside sight, unworked or not.', description: 'Older than the grove it came out of, and the grove was there first.' },
  { key: 'deepreach', name: 'Deepreach', slot: 'pickaxe', rarity: 'legendary', tradeable: true, stat: 'yield', value: 0.14, palette: 'iron', station: 'guild', maxDurability: 240, inputs: { mythril_ore: 5, meteoric_iron: 10, skysteel: 6, flux_salt: 6, reinforced_frame: 3, core: 1 }, description: 'Made for seams that start below where anyone has dug.' },
  { key: 'mothervein', name: 'Mothervein', slot: 'pickaxe', rarity: 'unique', tradeable: false, stat: 'yield', value: 0.15, palette: 'iron', maxDurability: 260, perk: 'Names the seam a mountain hex is hiding before the first swing.', description: 'It hums on the walk in, and louder the closer you get.' },
  { key: 'farshot', name: 'Farshot', slot: 'bow', rarity: 'legendary', tradeable: true, stat: 'yield', value: 0.14, palette: 'pelt', station: 'guild', maxDurability: 240, inputs: { beastfang_hide: 5, dire_pelt: 10, lacquered_hide: 6, horn: 6, reinforced_frame: 3, core: 1 }, description: 'Loosed from the treeline. Nothing on the range hears the first one.' },
  { key: 'the_quiet_mile', name: 'The Quiet Mile', slot: 'bow', rarity: 'unique', tradeable: false, stat: 'yield', value: 0.15, palette: 'pelt', maxDurability: 260, perk: 'A herd will not leave the hex you are standing on.', description: 'Drawn once at the treeline. Nothing on the range has ever heard it.' },
  { key: 'hillbreaker', name: 'Hillbreaker', slot: 'hammer', rarity: 'legendary', tradeable: true, stat: 'yield', value: 0.14, palette: 'stone', station: 'guild', maxDurability: 240, inputs: { obsidian_shard: 5, granite: 10, polished_granite: 6, whetgrit: 6, reinforced_frame: 3, core: 1 }, description: 'The face does not chip. It opens, all at once, along a line you chose.' },
  { key: 'the_standing_stone', name: 'The Standing Stone', slot: 'hammer', rarity: 'unique', tradeable: false, stat: 'yield', value: 0.15, palette: 'stone', maxDurability: 260, perk: 'Never breaks: it drops to its last point of durability and stops there.', description: 'Someone set it upright a long time ago and it has not moved since.' },
  { key: 'longreap', name: 'Longreap', slot: 'sickle', rarity: 'legendary', tradeable: true, stat: 'yield', value: 0.14, palette: 'fiber', station: 'guild', maxDurability: 240, inputs: { silkweave_fiber: 5, hemp: 10, canvas: 6, quench_reed: 6, reinforced_frame: 3, core: 1 }, description: 'A field in one pass, and the stubble left standing to the inch.' },
  { key: 'the_long_acre', name: 'The Long Acre', slot: 'sickle', rarity: 'unique', tradeable: false, stat: 'yield', value: 0.15, palette: 'fiber', maxDurability: 260, perk: 'A worked grassland hex regrows on its own clock, not the map’s.', description: 'The field it was named for is still cut every year by nobody.' },
  { key: 'wardencoat', name: 'Wardencoat', slot: 'armor', rarity: 'legendary', tradeable: true, stat: 'tripReduction', value: 0.14, palette: 'wood', station: 'guild', maxDurability: 240, inputs: { ironwood: 5, heartoak: 10, bentwood: 6, pine_pitch: 6, reinforced_frame: 3, core: 1 }, description: 'Grown, boiled and banded. Worn by people who walk the contested ring twice a day.' },
  { key: 'coat_of_ash', name: 'Coat of Ash', slot: 'armor', rarity: 'unique', tradeable: false, stat: 'tripReduction', value: 0.15, palette: 'wood', maxDurability: 260, perk: 'Weather on the contested ring costs you nothing at all.', description: 'Came out of the Ashpit on someone who did not.' },
  { key: 'leaguewalkers', name: 'Leaguewalkers', slot: 'boots', rarity: 'legendary', tradeable: true, stat: 'travelSpeed', value: 0.14, palette: 'pelt', station: 'guild', maxDurability: 240, inputs: { beastfang_hide: 5, dire_pelt: 10, lacquered_hide: 6, sinew: 6, reinforced_frame: 3, core: 1 }, description: 'Cut for the road between rings. The miles stop being the argument.' },
  { key: 'the_wanderers_debt', name: 'The Wanderer\'s Debt', slot: 'boots', rarity: 'unique', tradeable: false, stat: 'travelSpeed', value: 0.15, palette: 'pelt', maxDurability: 260, perk: 'The road pays Explorer experience whether you arrive or turn back.', description: 'Worn through and mended eleven times. None of the mending is yours.' },
  { key: 'steadyhands', name: 'Steadyhands', slot: 'gloves', rarity: 'legendary', tradeable: true, stat: 'processingSpeed', value: 0.14, palette: 'fiber', station: 'guild', maxDurability: 240, inputs: { silkweave_fiber: 5, hemp: 10, canvas: 6, beeswax: 6, reinforced_frame: 3, core: 1 }, description: 'Every line foreman in the capital knows the pattern and none can afford it.' },
  { key: 'coldforge', name: 'Coldforge', slot: 'gloves', rarity: 'unique', tradeable: false, stat: 'processingSpeed', value: 0.15, palette: 'fiber', maxDurability: 260, perk: 'A processing queue you are standing in never counts you as absent.', description: 'Warm to hold in any weather, which is the wrong way round.' },
]
