/**
 * Generated by scripts/gen_variants.py -- do not edit by hand.
 *
 * §5.3 -- four tile variants per biome, one per equipment rung, and the variant
 * is what decides which grade of material the hex gives up. The Tier 3 rare is
 * one of the four, so contested ground stops borrowing the base biome's sprite.
 */
import type { Biome, Material, Recipe, SkillKey, VariantKey } from './types'

export interface VariantDef {
  key: VariantKey
  grade: 'common' | 'uncommon' | 'rare' | 'epic'
  name: string
  material: string
  tint: string
  props: string
  weights: { outer: number; mid: number; inner: number }
}

export const BIOME_VARIANTS: Record<Biome, VariantDef[]> = {
  forest: [
    { key: 'forest', grade: 'common', name: 'Forest', material: 'wood', tint: '#5f8058', props: 'conifers', weights: { outer: 1.0, mid: 0.7, inner: 0.42 } },
    { key: 'forest_uncommon', grade: 'uncommon', name: 'Hardwood Stand', material: 'hardwood', tint: '#6b8a4e', props: 'broadleaf', weights: { outer: 0.0, mid: 0.3, inner: 0.25 } },
    { key: 'forest_rare', grade: 'rare', name: 'Old Growth', material: 'heartoak', tint: '#46654a', props: 'giants', weights: { outer: 0.0, mid: 0.0, inner: 0.15 } },
    { key: 'forest_epic', grade: 'epic', name: 'Ironwood Grove', material: 'ironwood', tint: '#55705f', props: 'ironwood', weights: { outer: 0.0, mid: 0.0, inner: 0.18 } },
  ],
  mountain: [
    { key: 'mountain', grade: 'common', name: 'Mountain', material: 'iron_ore', tint: '#6d8399', props: 'peaks', weights: { outer: 1.0, mid: 0.7, inner: 0.42 } },
    { key: 'mountain_uncommon', grade: 'uncommon', name: 'Hematite Ridge', material: 'hematite', tint: '#8a7a72', props: 'banded', weights: { outer: 0.0, mid: 0.3, inner: 0.25 } },
    { key: 'mountain_rare', grade: 'rare', name: 'Crater Field', material: 'meteoric_iron', tint: '#5c6b7d', props: 'crater', weights: { outer: 0.0, mid: 0.0, inner: 0.15 } },
    { key: 'mountain_epic', grade: 'epic', name: 'Mythril Seam', material: 'mythril_ore', tint: '#7d93a8', props: 'mythril', weights: { outer: 0.0, mid: 0.0, inner: 0.18 } },
  ],
  plains: [
    { key: 'plains', grade: 'common', name: 'Plains', material: 'pelt', tint: '#b08a5a', props: 'tufts', weights: { outer: 1.0, mid: 0.7, inner: 0.42 } },
    { key: 'plains_uncommon', grade: 'uncommon', name: 'Herd Range', material: 'thick_pelt', tint: '#bb9a63', props: 'grazed', weights: { outer: 0.0, mid: 0.3, inner: 0.25 } },
    { key: 'plains_rare', grade: 'rare', name: 'Dire Range', material: 'dire_pelt', tint: '#96703f', props: 'bones', weights: { outer: 0.0, mid: 0.0, inner: 0.15 } },
    { key: 'plains_epic', grade: 'epic', name: 'Beastfang Reach', material: 'beastfang_hide', tint: '#a37452', props: 'fangs', weights: { outer: 0.0, mid: 0.0, inner: 0.18 } },
  ],
  badlands: [
    { key: 'badlands', grade: 'common', name: 'Badlands', material: 'stone', tint: '#96604c', props: 'shards', weights: { outer: 1.0, mid: 0.7, inner: 0.42 } },
    { key: 'badlands_uncommon', grade: 'uncommon', name: 'Basalt Flats', material: 'basalt', tint: '#7a5347', props: 'columns', weights: { outer: 0.0, mid: 0.3, inner: 0.25 } },
    { key: 'badlands_rare', grade: 'rare', name: 'Granite Shelf', material: 'granite', tint: '#a1756a', props: 'shelf', weights: { outer: 0.0, mid: 0.0, inner: 0.15 } },
    { key: 'badlands_epic', grade: 'epic', name: 'Obsidian Flow', material: 'obsidian_shard', tint: '#5f4a52', props: 'glass', weights: { outer: 0.0, mid: 0.0, inner: 0.18 } },
  ],
  grassland: [
    { key: 'grassland', grade: 'common', name: 'Grassland', material: 'fiber', tint: '#a8a05c', props: 'tufts', weights: { outer: 1.0, mid: 0.7, inner: 0.42 } },
    { key: 'grassland_uncommon', grade: 'uncommon', name: 'Flax Meadow', material: 'flax', tint: '#b6b073', props: 'flowering', weights: { outer: 0.0, mid: 0.3, inner: 0.25 } },
    { key: 'grassland_rare', grade: 'rare', name: 'Hemp Field', material: 'hemp', tint: '#8f9552', props: 'tall', weights: { outer: 0.0, mid: 0.0, inner: 0.15 } },
    { key: 'grassland_epic', grade: 'epic', name: 'Silkweave Fen', material: 'silkweave_fiber', tint: '#9fa878', props: 'silk', weights: { outer: 0.0, mid: 0.0, inner: 0.18 } },
  ],
}

/** §13.2 -- the hex fill for a variant. Solid, never alpha. */
export const VARIANT_TINT: Record<VariantKey, string> = {
  forest: '#5f8058',
  forest_uncommon: '#6b8a4e',
  forest_rare: '#46654a',
  forest_epic: '#55705f',
  mountain: '#6d8399',
  mountain_uncommon: '#8a7a72',
  mountain_rare: '#5c6b7d',
  mountain_epic: '#7d93a8',
  plains: '#b08a5a',
  plains_uncommon: '#bb9a63',
  plains_rare: '#96703f',
  plains_epic: '#a37452',
  badlands: '#96604c',
  badlands_uncommon: '#7a5347',
  badlands_rare: '#a1756a',
  badlands_epic: '#5f4a52',
  grassland: '#a8a05c',
  grassland_uncommon: '#b6b073',
  grassland_rare: '#8f9552',
  grassland_epic: '#9fa878',
}

/** What the map calls the ground under your feet. */
export const VARIANT_LABEL: Record<VariantKey, string> = {
  forest: 'Forest',
  forest_uncommon: 'Hardwood Stand',
  forest_rare: 'Old Growth',
  forest_epic: 'Ironwood Grove',
  mountain: 'Mountain',
  mountain_uncommon: 'Hematite Ridge',
  mountain_rare: 'Crater Field',
  mountain_epic: 'Mythril Seam',
  plains: 'Plains',
  plains_uncommon: 'Herd Range',
  plains_rare: 'Dire Range',
  plains_epic: 'Beastfang Reach',
  badlands: 'Badlands',
  badlands_uncommon: 'Basalt Flats',
  badlands_rare: 'Granite Shelf',
  badlands_epic: 'Obsidian Flow',
  grassland: 'Grassland',
  grassland_uncommon: 'Flax Meadow',
  grassland_rare: 'Hemp Field',
  grassland_epic: 'Silkweave Fen',
}

export const VARIANT_DESCRIPTION: Record<VariantKey, string> = {
  forest: 'Close conifer, worked since anybody got here. Where the line starts.',
  forest_uncommon: 'Broadleaf, close-grown, and dark underneath.',
  forest_rare: 'Nothing here has been cut in living memory.',
  forest_epic: 'The trunks ring when struck. Contested ground.',
  mountain: 'Bare rock and scree above the treeline. Every range begins as this.',
  mountain_uncommon: 'The scree runs red where the rain has been at it.',
  mountain_rare: 'Something landed here, and the ground has not closed over it.',
  mountain_epic: 'A pale line through the rock that hums. Contested ground.',
  plains: 'Open grazing. The herds cross it and so does everybody else.',
  plains_uncommon: 'Cropped short and trodden through. They come back to it.',
  plains_rare: 'The herds keep off this stretch, and they are right to.',
  plains_epic: 'Bones at the treeline, none of them small. Contested ground.',
  badlands: 'Broken shale on burnt ground. It gives up stone and very little else.',
  badlands_uncommon: 'Cooled into columns and cracked square along them.',
  badlands_rare: 'A speckled slab the weather has never got under.',
  badlands_epic: 'Black glass, still sharp where it broke. Contested ground.',
  grassland: 'Waist-high and going nowhere. The cheapest fibre there is.',
  grassland_uncommon: 'Blue at the top for a week a year, then worth cutting.',
  grassland_rare: 'Stems over head height. You lose sight of the next hex in it.',
  grassland_epic: 'Something has been spinning in the tall grass. Contested ground.',
}

export const VARIANT_RAW: Material[] = [
  { key: 'hardwood', name: 'Hardwood', tier: 1, biome: 'forest', palette: 'wood', npcPrice: 4, description: 'Broadleaf, felled standing. Twice the weight of green pine and worth carrying.' },
  { key: 'heartoak', name: 'Heartoak', tier: 1, biome: 'forest', palette: 'wood', npcPrice: 7, description: 'The dark core of something that outlived everyone who saw it planted.' },
  { key: 'hematite', name: 'Hematite', tier: 1, biome: 'mountain', palette: 'iron', npcPrice: 5, description: 'Ore rich enough that the slag heap is barely worth picking over.' },
  { key: 'meteoric_iron', name: 'Meteoric Iron', tier: 1, biome: 'mountain', palette: 'iron', npcPrice: 9, description: 'Came down in the crater field. Takes an edge nothing smelted can hold.' },
  { key: 'thick_pelt', name: 'Thick Pelt', tier: 1, biome: 'plains', palette: 'pelt', npcPrice: 5, description: 'Winter coat off a full-grown animal. Heavy, and it keeps its shape.' },
  { key: 'dire_pelt', name: 'Dire Pelt', tier: 1, biome: 'plains', palette: 'pelt', npcPrice: 9, description: 'Off something that had no natural enemies until you turned up.' },
  { key: 'basalt', name: 'Basalt', tier: 1, biome: 'badlands', palette: 'stone', npcPrice: 4, description: 'Cooled in columns, and it splits along them. Harder than the shale next door.' },
  { key: 'granite', name: 'Granite', tier: 1, biome: 'badlands', palette: 'stone', npcPrice: 8, description: 'Speckled and stubborn. It blunts what you dress it with.' },
  { key: 'flax', name: 'Flax', tier: 1, biome: 'grassland', palette: 'fiber', npcPrice: 4, description: 'Retted in the ditch for a fortnight. Spins finer than field grass ever will.' },
  { key: 'hemp', name: 'Hemp', tier: 1, biome: 'grassland', palette: 'fiber', npcPrice: 7, description: 'Stems taller than a man. Nothing ordinary breaks a rope of it.' },
]

export const VARIANT_REFINED: Material[] = [
  { key: 'beams', name: 'Beams', tier: 2, palette: 'wood', npcPrice: 14, description: 'Squared off the log rather than sawn thin. Takes a load without complaining.' },
  { key: 'bentwood', name: 'Bentwood', tier: 2, palette: 'wood', npcPrice: 26, description: 'Steamed, bent round a form, and left to set. It holds the curve forever.' },
  { key: 'steel_ingots', name: 'Steel Ingots', tier: 2, palette: 'iron', npcPrice: 18, description: 'Carbon worked through the iron. Springs back where plain bar stays bent.' },
  { key: 'skysteel', name: 'Skysteel', tier: 2, palette: 'iron', npcPrice: 32, description: 'Folded out of what fell. Pale, and it rings a long time after the strike.' },
  { key: 'boiled_leather', name: 'Boiled Leather', tier: 2, palette: 'pelt', npcPrice: 16, description: 'Boiled hard and molded wet. Sets like a shell and weighs nothing.' },
  { key: 'lacquered_hide', name: 'Lacquered Hide', tier: 2, palette: 'pelt', npcPrice: 30, description: 'Layered, lacquered, and left in the dark to cure. Turns a blade.' },
  { key: 'dressed_basalt', name: 'Dressed Basalt', tier: 2, palette: 'stone', npcPrice: 15, description: 'Squared out of the column. Every face is already flat; you only true it.' },
  { key: 'polished_granite', name: 'Polished Granite', tier: 2, palette: 'stone', npcPrice: 28, description: 'Ground down through four grits. The finish is what makes it last.' },
  { key: 'linen', name: 'Linen', tier: 2, palette: 'fiber', npcPrice: 13, description: 'Woven off the flax line. Cool, strong, and it takes a dye.' },
  { key: 'canvas', name: 'Canvas', tier: 2, palette: 'fiber', npcPrice: 25, description: 'Hemp beaten flat and woven close. Rain runs off it and rope does not cut it.' },
]

/** §6 -- one line per grade, same 3:1 as the five base lines. */
export const VARIANT_PROCESSING: Recipe[] = [
  { key: 'beams', name: 'Saw Beams', input: 'hardwood', inputQty: 3, output: 'beams', outputQty: 1, baseSeconds: 16 * 60, skill: 'woodcutting' },
  { key: 'bentwood', name: 'Saw Bentwood', input: 'heartoak', inputQty: 3, output: 'bentwood', outputQty: 1, baseSeconds: 22 * 60, skill: 'woodcutting' },
  { key: 'steel_ingots', name: 'Smelt Steel Ingots', input: 'hematite', inputQty: 3, output: 'steel_ingots', outputQty: 1, baseSeconds: 19 * 60, skill: 'mining' },
  { key: 'skysteel', name: 'Smelt Skysteel', input: 'meteoric_iron', inputQty: 3, output: 'skysteel', outputQty: 1, baseSeconds: 26 * 60, skill: 'mining' },
  { key: 'boiled_leather', name: 'Tan Boiled Leather', input: 'thick_pelt', inputQty: 3, output: 'boiled_leather', outputQty: 1, baseSeconds: 17 * 60, skill: 'hunting' },
  { key: 'lacquered_hide', name: 'Tan Lacquered Hide', input: 'dire_pelt', inputQty: 3, output: 'lacquered_hide', outputQty: 1, baseSeconds: 24 * 60, skill: 'hunting' },
  { key: 'dressed_basalt', name: 'Dress Dressed Basalt', input: 'basalt', inputQty: 3, output: 'dressed_basalt', outputQty: 1, baseSeconds: 16 * 60, skill: 'quarrying' },
  { key: 'polished_granite', name: 'Dress Polished Granite', input: 'granite', inputQty: 3, output: 'polished_granite', outputQty: 1, baseSeconds: 23 * 60, skill: 'quarrying' },
  { key: 'linen', name: 'Weave Linen', input: 'flax', inputQty: 3, output: 'linen', outputQty: 1, baseSeconds: 15 * 60, skill: 'harvesting' },
  { key: 'canvas', name: 'Weave Canvas', input: 'hemp', inputQty: 3, output: 'canvas', outputQty: 1, baseSeconds: 21 * 60, skill: 'harvesting' },
]

/** §13.2 -- which prop treatment props.ts draws for a variant. */
export const VARIANT_PROPS: Record<VariantKey, string> = {
  forest: 'conifers',
  forest_uncommon: 'broadleaf',
  forest_rare: 'giants',
  forest_epic: 'ironwood',
  mountain: 'peaks',
  mountain_uncommon: 'banded',
  mountain_rare: 'crater',
  mountain_epic: 'mythril',
  plains: 'tufts',
  plains_uncommon: 'grazed',
  plains_rare: 'bones',
  plains_epic: 'fangs',
  badlands: 'shards',
  badlands_uncommon: 'columns',
  badlands_rare: 'shelf',
  badlands_epic: 'glass',
  grassland: 'tufts',
  grassland_uncommon: 'flowering',
  grassland_rare: 'tall',
  grassland_epic: 'silk',
}

/** §5.3 -- which ground a material comes off, for the almanac. */
export const VARIANT_BY_MATERIAL: Record<string, VariantKey> = {
  wood: 'forest',
  hardwood: 'forest_uncommon',
  heartoak: 'forest_rare',
  ironwood: 'forest_epic',
  iron_ore: 'mountain',
  hematite: 'mountain_uncommon',
  meteoric_iron: 'mountain_rare',
  mythril_ore: 'mountain_epic',
  pelt: 'plains',
  thick_pelt: 'plains_uncommon',
  dire_pelt: 'plains_rare',
  beastfang_hide: 'plains_epic',
  stone: 'badlands',
  basalt: 'badlands_uncommon',
  granite: 'badlands_rare',
  obsidian_shard: 'badlands_epic',
  fiber: 'grassland',
  flax: 'grassland_uncommon',
  hemp: 'grassland_rare',
  silkweave_fiber: 'grassland_epic',
}

/**
 * §5.2 -- how far in you have to walk before a grade turns up at all.
 * Derived from the weight table, so it cannot disagree with the roll.
 */
export const VARIANT_RINGS: Record<VariantKey, string[]> = {
  forest: ['outer', 'mid', 'inner'],
  forest_uncommon: ['mid', 'inner'],
  forest_rare: ['inner'],
  forest_epic: ['inner'],
  mountain: ['outer', 'mid', 'inner'],
  mountain_uncommon: ['mid', 'inner'],
  mountain_rare: ['inner'],
  mountain_epic: ['inner'],
  plains: ['outer', 'mid', 'inner'],
  plains_uncommon: ['mid', 'inner'],
  plains_rare: ['inner'],
  plains_epic: ['inner'],
  badlands: ['outer', 'mid', 'inner'],
  badlands_uncommon: ['mid', 'inner'],
  badlands_rare: ['inner'],
  badlands_epic: ['inner'],
  grassland: ['outer', 'mid', 'inner'],
  grassland_uncommon: ['mid', 'inner'],
  grassland_rare: ['inner'],
  grassland_epic: ['inner'],
}

/** §7.2 -- which gathering line a grade belongs to. */
export const VARIANT_SKILL: Record<string, SkillKey> = {
  hardwood: 'woodcutting',
  heartoak: 'woodcutting',
  hematite: 'mining',
  meteoric_iron: 'mining',
  thick_pelt: 'hunting',
  dire_pelt: 'hunting',
  basalt: 'quarrying',
  granite: 'quarrying',
  flax: 'harvesting',
  hemp: 'harvesting',
}
