<script setup lang="ts">
/** Renders a procedurally generated SVG string. All markup is generated by
 *  src/icons/procedural.ts from numeric inputs -- never user content. */
defineProps<{ svg: string; boxed?: boolean; size?: number }>()
</script>

<template>
  <span
    class="svg-icon"
    :class="{ 'icon-box': boxed }"
    :style="boxed ? { width: `${(size ?? 32) + 12}px`, height: `${(size ?? 32) + 12}px` } : undefined"
    v-html="svg"
  />
</template>

<style scoped>
.svg-icon {
  display: inline-grid;
  place-items: center;
  line-height: 0;
}
</style>
