<?php

declare(strict_types=1);

namespace App\Game;

/**
 * Generated by scripts/gen_components.py -- do not edit by hand.
 *
 * Ten craft components (§4), emitted into PHP and TypeScript from one spec so
 * the two catalogs cannot drift.
 */
final class Components
{
    /**
     * §4 Tier 1 -- craft components, biome-locked, the smith's and the
     * armorer's raw stock. Two per biome, so one recipe can want two different
     * things off a single kind of ground.
     */
    public const CRAFT = [
        'heartknot' => ['name' => 'Heartknot', 'tier' => 1, 'biome' => 'forest', 'palette' => 'wood', 'bench' => 'weapon', 'npcPrice' => 4, 'description' => 'The knot where a limb met the trunk. Blunts a saw and takes a haft.'],
        'pine_pitch' => ['name' => 'Pine Pitch', 'tier' => 1, 'biome' => 'forest', 'palette' => 'wood', 'bench' => 'armor', 'npcPrice' => 3, 'description' => 'Boiled down off the bark. Everything it touches stays touched.'],
        'flux_salt' => ['name' => 'Flux Salt', 'tier' => 1, 'biome' => 'mountain', 'palette' => 'iron', 'bench' => 'weapon', 'npcPrice' => 4, 'description' => 'Thrown on the weld so the join takes. Without it, iron only meets iron.'],
        'slate_scale' => ['name' => 'Slate Scale', 'tier' => 1, 'biome' => 'mountain', 'palette' => 'iron', 'bench' => 'armor', 'npcPrice' => 3, 'description' => 'Splits off the seam in plates a thumb across. Overlaps like it was asked to.'],
        'horn' => ['name' => 'Horn', 'tier' => 1, 'biome' => 'plains', 'palette' => 'pelt', 'bench' => 'weapon', 'npcPrice' => 4, 'description' => 'Cut off the herd bull and boiled soft. It remembers the shape you leave it.'],
        'sinew' => ['name' => 'Sinew', 'tier' => 1, 'biome' => 'plains', 'palette' => 'pelt', 'bench' => 'armor', 'npcPrice' => 3, 'description' => 'Dried to a cord and split with the teeth. Stronger than anything spun.'],
        'whetgrit' => ['name' => 'Whetgrit', 'tier' => 1, 'biome' => 'badlands', 'palette' => 'stone', 'bench' => 'weapon', 'npcPrice' => 3, 'description' => 'Sharp sand off the scree. It is what puts an edge on everything else.'],
        'tar_seep' => ['name' => 'Tar Seep', 'tier' => 1, 'biome' => 'badlands', 'palette' => 'stone', 'bench' => 'armor', 'npcPrice' => 3, 'description' => 'Skimmed cold off a standing pool. Keeps the wet out of a boot for a season.'],
        'quench_reed' => ['name' => 'Quench Reed', 'tier' => 1, 'biome' => 'grassland', 'palette' => 'fiber', 'bench' => 'weapon', 'npcPrice' => 2, 'description' => 'Green stems packed round a hot blade. It cools slow, and slow is what holds.'],
        'beeswax' => ['name' => 'Beeswax', 'tier' => 1, 'biome' => 'grassland', 'palette' => 'fiber', 'bench' => 'armor', 'npcPrice' => 2, 'description' => 'Rendered off the comb. Waterproofs a seam and quiets a hinge.'],
    ];
}
