<?php

declare(strict_types=1);

namespace App\Game;

/**
 * Generated by scripts/gen_hunts.py -- do not edit by hand.
 *
 * §5.5 -- the hunt. What mining a plains hex used to be.
 *
 * An animal stands on every workable forest and grassland hex, and it is **always
 * there**: a pack is a chance and this is not, because this is not a hazard, it is
 * the hunting line's ground. It moves on the pack's own two-hour bucket, and
 * killing it clears it exactly as fighting a pack clears that.
 *
 * **It does not pin.** A pack owns the hex it stands on (§9.5.3), which is a
 * hazard a player walks around; an animal on every hex of two countries doing the
 * same would make those countries impassable. It is a hook on a hex that otherwise
 * works normally -- the same standing §9.5.7 gives a corpse.
 *
 * **The GRADE is the ladder, and it is the plains variant table moved onto the
 * creature.** A hex used to carry Plains / Herd Range / Dire Range / Beastfang
 * Reach; the animal carries it now, on the same weights -- which is what keeps
 * Beastfang Hide contested-only without a rule of its own (§2: a Tier 3 on the
 * safe rim is the grind->NFT path the threat model exists to close).
 *
 * **Two countries of four**, one animal per grade. A roster shared between them
 * would make forest and grassland the same walk, and §9.5.2 has just finished
 * making that argument about monsters.
 */
final class Hunts
{
    /** §5.5 -- the countries an animal stands on, and no others. */
    public const BIOMES = ['forest', 'grassland'];

    /** §5.3 -- the grade ladder, and what each rung gives up. */
    public const GRADES = [
        'common' => ['material' => 'pelt', 'weights' => ['outer' => 0.975, 'mid' => 0.68, 'inner' => 0.42]],
        'uncommon' => ['material' => 'thick_pelt', 'weights' => ['outer' => 0.02, 'mid' => 0.3, 'inner' => 0.25]],
        'rare' => ['material' => 'dire_pelt', 'weights' => ['outer' => 0.005, 'mid' => 0.02, 'inner' => 0.15]],
        'contested' => ['material' => 'beastfang_hide', 'weights' => ['outer' => 0.0, 'mid' => 0.0, 'inner' => 0.18]],
    ];

    /** §5.5 -- the roster. Keyed by animal, one per (biome, grade). */
    public const ROSTER = [
        'roe_deer' => ['name' => 'Roe Deer', 'biome' => 'forest', 'grade' => 'common', 'material' => 'pelt', 'description' => 'Feeding at the edge of the trees, and gone into them the moment you are seen.'],
        'wood_boar' => ['name' => 'Wood Boar', 'biome' => 'forest', 'grade' => 'uncommon', 'material' => 'thick_pelt', 'description' => 'Rooting under the mast. It has no reason to run and knows it.'],
        'bracken_elk' => ['name' => 'Bracken Elk', 'biome' => 'forest', 'grade' => 'rare', 'material' => 'dire_pelt', 'description' => 'Shoulder-high in the fern with a rack it has to turn sideways to walk.'],
        'ironhide_stag' => ['name' => 'Ironhide Stag', 'biome' => 'forest', 'grade' => 'contested', 'material' => 'beastfang_hide', 'description' => 'Nothing in the wood has taken one down in living memory. You may try.'],
        'field_doe' => ['name' => 'Field Doe', 'biome' => 'grassland', 'grade' => 'common', 'material' => 'pelt', 'description' => 'Standing in the seed heads with its ears up, which is how you find it.'],
        'horned_ram' => ['name' => 'Horned Ram', 'biome' => 'grassland', 'grade' => 'uncommon', 'material' => 'thick_pelt', 'description' => 'Comes down the slope at you rather than away, every time.'],
        'sedge_auroch' => ['name' => 'Sedge Auroch', 'biome' => 'grassland', 'grade' => 'rare', 'material' => 'dire_pelt', 'description' => 'Older than the settlement it grazes past, and heavier than the gate.'],
        'beastfang_sire' => ['name' => 'Beastfang Sire', 'biome' => 'grassland', 'grade' => 'contested', 'material' => 'beastfang_hide', 'description' => 'The hide is named for it. So is most of what it has eaten.'],
    ];

    /**
     * §4 Tier 1 -- the hunting line's own raw ladder.
     *
     * `source` rather than `biome`, and that is the whole of what
     * makes hunting different from the other four lines: these come
     * off a creature rather than off a country, so nothing here is
     * locked to ground and nothing reads a biome to find it.
     */
    public const RAW = [
        'pelt' => ['name' => 'Pelt', 'tier' => 1, 'source' => 'hunt', 'grade' => 'common', 'palette' => 'pelt', 'npcPrice' => 3, 'description' => 'Rough hide, taken off something that was using it.'],
        'thick_pelt' => ['name' => 'Thick Pelt', 'tier' => 1, 'source' => 'hunt', 'grade' => 'uncommon', 'palette' => 'pelt', 'npcPrice' => 5, 'description' => 'Winter coat off a full-grown animal. Heavy, and it keeps its shape.'],
        'dire_pelt' => ['name' => 'Dire Pelt', 'tier' => 1, 'source' => 'hunt', 'grade' => 'rare', 'palette' => 'pelt', 'npcPrice' => 9, 'description' => 'Off something that had no natural enemies until you turned up.'],
        'beastfang_hide' => ['name' => 'Beastfang Hide', 'tier' => 1, 'source' => 'hunt', 'grade' => 'contested', 'palette' => 'pelt', 'npcPrice' => 0, 'description' => 'Taken off something that fought back.'],
    ];

    /** §4 Tier 2 -- what each rung tans into. Not locked to anything. */
    public const REFINED = [
        'leather' => ['name' => 'Leather', 'tier' => 2, 'palette' => 'pelt', 'npcPrice' => 8, 'description' => 'Scraped, soaked and worked soft. The first thing a tannery is for.'],
        'boiled_leather' => ['name' => 'Boiled Leather', 'tier' => 2, 'palette' => 'pelt', 'npcPrice' => 16, 'description' => 'Boiled hard and molded wet. Sets like a shell and weighs nothing.'],
        'lacquered_hide' => ['name' => 'Lacquered Hide', 'tier' => 2, 'palette' => 'pelt', 'npcPrice' => 30, 'description' => 'Layered, lacquered, and left in the dark to cure. Turns a blade.'],
    ];

    /** §6 -- the Tanner's line, one recipe per rung. */
    public const PROCESSING = [
        'tan_leather' => ['name' => 'Tan Leather', 'input' => 'pelt', 'inputQty' => 3, 'output' => 'leather', 'outputQty' => 1, 'baseSeconds' => 13 * 60, 'skill' => 'hunting'],
        'tan_boiled_leather' => ['name' => 'Tan Boiled Leather', 'input' => 'thick_pelt', 'inputQty' => 3, 'output' => 'boiled_leather', 'outputQty' => 1, 'baseSeconds' => 17 * 60, 'skill' => 'hunting'],
        'tan_lacquered_hide' => ['name' => 'Tan Lacquered Hide', 'input' => 'dire_pelt', 'inputQty' => 3, 'output' => 'lacquered_hide', 'outputQty' => 1, 'baseSeconds' => 24 * 60, 'skill' => 'hunting'],
    ];

    /** §7.2 -- every rung of this ladder belongs to the hunting line. */
    public const SKILL_FOR_MATERIAL = [
        'pelt' => 'hunting',
        'thick_pelt' => 'hunting',
        'dire_pelt' => 'hunting',
        'beastfang_hide' => 'hunting',
    ];

    /** Biome -> grade -> which animal that is. */
    public const BY_BIOME_GRADE = [
        'forest' => [
            'common' => 'roe_deer',
            'uncommon' => 'wood_boar',
            'rare' => 'bracken_elk',
            'contested' => 'ironhide_stag',
        ],
        'grassland' => [
            'common' => 'field_doe',
            'uncommon' => 'horned_ram',
            'rare' => 'sedge_auroch',
            'contested' => 'beastfang_sire',
        ],
    ];
}
