<?php

declare(strict_types=1);

namespace App\Game;

/**
 * Generated by scripts/gen_monsters.py -- do not edit by hand.
 *
 * §9.5.2 -- twenty-five monsters, five to a biome, and **a country's five stand on
 * that country and nowhere else**. Walking from forest into badlands changes what
 * is on the road, which is what makes crossing the map a thing you look at rather
 * than a distance you spend.
 *
 * The BIOME decides which five you can meet at all; the RING decides which of them
 * are out. A ring fields its own tier and the one outside it, so walking inward you
 * meet one you already know how to fight and one you do not -- and the rim fields
 * both of its tier ones, because a first country should not be a single creature
 * repeated.
 *
 * **A biome changes what you meet, never how hard it is.** The pair comes off
 * (tier, profile) and nothing else, so a tier-1 brute hits for the same on every
 * kind of ground and two prospectors on the same ring are on the same ladder
 * whatever country they are standing in. What a biome is worth is its own drop
 * (§9.5.8), not an easier or harder fight.
 *
 * No two monsters in a biome share a (tier, profile) pair. §9.5.2 gives the
 * silhouette to the profile and the hide to the tier, so biome + tier + profile
 * already identifies a creature -- and without that rule two of a country's five
 * come out as the same animal in the same colour.
 *
 * `attack` and `defense` are FLAT, and they are not the percentage stats of the
 * same name: §8.1's ceiling is +15%, and a fight cannot be decided by a swing that
 * small. The profile is what a player reads -- a brute is high attack and low
 * defense, a carapace the reverse, a swift one is middling in both and wears a
 * weapon harder for it.
 */
final class Monsters
{
    /** §9.5.2 -- the roster. Flat attack, defense and HP, never percentages. */
    public const ROSTER = [
        'moss_hound' => ['name' => 'Moss Hound', 'biome' => 'forest', 'tier' => 1, 'level' => 5, 'profile' => 'brute', 'attack' => 1200, 'defense' => 500, 'hp' => 5200, 'wearBias' => 1.0, 'gold' => [5, 10], 'plate' => 'cracked_carapace', 'ichor' => 'thin_ichor', 'rareSpoil' => 'bone_plate', 'biomeSpoil' => 'sap_matted_fur', 'biomeLeaving' => 'trampled_fern', 'description' => 'Runs the treeline in threes and takes the slowest thing on the road.'],
        'thicket_darter' => ['name' => 'Thicket Darter', 'biome' => 'forest', 'tier' => 1, 'level' => 2, 'profile' => 'swift', 'attack' => 900, 'defense' => 800, 'hp' => 4500, 'wearBias' => 1.3, 'gold' => [5, 10], 'plate' => 'cracked_carapace', 'ichor' => 'thin_ichor', 'rareSpoil' => 'bone_plate', 'biomeSpoil' => 'sap_matted_fur', 'biomeLeaving' => 'trampled_fern', 'description' => 'Goes through the undergrowth rather than round it, and is out the far side already.'],
        'thornback' => ['name' => 'Thornback', 'biome' => 'forest', 'tier' => 2, 'level' => 8, 'profile' => 'carapace', 'attack' => 1300, 'defense' => 2600, 'hp' => 9400, 'wearBias' => 1.0, 'gold' => [15, 28], 'plate' => 'bone_plate', 'ichor' => 'black_blood', 'rareSpoil' => 'scaled_hide', 'biomeSpoil' => 'sap_matted_fur', 'biomeLeaving' => 'trampled_fern', 'description' => 'Every quill points out. Hitting it costs you more than missing does.'],
        'rootbound_elder' => ['name' => 'Rootbound Elder', 'biome' => 'forest', 'tier' => 3, 'level' => 29, 'profile' => 'brute', 'attack' => 3600, 'defense' => 1700, 'hp' => 18400, 'wearBias' => 1.0, 'gold' => [33, 58], 'plate' => 'scaled_hide', 'ichor' => 'bile_sac', 'rareSpoil' => 'warped_barb', 'biomeSpoil' => 'sap_matted_fur', 'biomeLeaving' => 'trampled_fern', 'description' => 'Stood in one place long enough to grow into it, and pulls free when you get close.'],
        'pale_stalker' => ['name' => 'Pale Stalker', 'biome' => 'forest', 'tier' => 4, 'level' => 44, 'profile' => 'swift', 'attack' => 5200, 'defense' => 4000, 'hp' => 24000, 'wearBias' => 1.5, 'gold' => [66, 115], 'plate' => 'warped_barb', 'ichor' => 'ember_gland', 'rareSpoil' => 'revenant_plate', 'biomeSpoil' => 'sap_matted_fur', 'biomeLeaving' => 'trampled_fern', 'description' => 'Keeps pace a ring behind you for a day, and closes on the hex you stop at.'],
        'pick_scarred_ram' => ['name' => 'Pick-Scarred Ram', 'biome' => 'mountain', 'tier' => 1, 'level' => 5, 'profile' => 'brute', 'attack' => 1200, 'defense' => 500, 'hp' => 5200, 'wearBias' => 1.0, 'gold' => [5, 10], 'plate' => 'cracked_carapace', 'ichor' => 'thin_ichor', 'rareSpoil' => 'bone_plate', 'biomeSpoil' => 'ore_crusted_chitin', 'biomeLeaving' => 'shale_grit', 'description' => 'Somebody swung at it once. It has been coming back down the scree ever since.'],
        'talus_creeper' => ['name' => 'Talus Creeper', 'biome' => 'mountain', 'tier' => 1, 'level' => 1, 'profile' => 'carapace', 'attack' => 600, 'defense' => 1100, 'hp' => 4000, 'wearBias' => 1.0, 'gold' => [5, 10], 'plate' => 'cracked_carapace', 'ichor' => 'thin_ichor', 'rareSpoil' => 'bone_plate', 'biomeSpoil' => 'ore_crusted_chitin', 'biomeLeaving' => 'shale_grit', 'description' => 'Wedged in the loose rock with its shell uppermost, and the rock is the shell.'],
        'slag_ogre' => ['name' => 'Slag Ogre', 'biome' => 'mountain', 'tier' => 2, 'level' => 14, 'profile' => 'brute', 'attack' => 2700, 'defense' => 1200, 'hp' => 12100, 'wearBias' => 1.0, 'gold' => [15, 28], 'plate' => 'bone_plate', 'ichor' => 'black_blood', 'rareSpoil' => 'scaled_hide', 'biomeSpoil' => 'ore_crusted_chitin', 'biomeLeaving' => 'shale_grit', 'description' => 'Came down off a spoil heap and has been swinging the same girder since.'],
        'ridge_wyrm' => ['name' => 'Ridge Wyrm', 'biome' => 'mountain', 'tier' => 3, 'level' => 22, 'profile' => 'swift', 'attack' => 3000, 'defense' => 2300, 'hp' => 16000, 'wearBias' => 1.5, 'gold' => [33, 58], 'plate' => 'scaled_hide', 'ichor' => 'bile_sac', 'rareSpoil' => 'warped_barb', 'biomeSpoil' => 'ore_crusted_chitin', 'biomeLeaving' => 'shale_grit', 'description' => 'Fast over broken ground and faster over you. It blunts whatever it is hit with.'],
        'mythril_warden' => ['name' => 'Mythril Warden', 'biome' => 'mountain', 'tier' => 4, 'level' => 38, 'profile' => 'carapace', 'attack' => 3200, 'defense' => 5800, 'hp' => 21600, 'wearBias' => 1.0, 'gold' => [66, 115], 'plate' => 'warped_barb', 'ichor' => 'ember_gland', 'rareSpoil' => 'revenant_plate', 'biomeSpoil' => 'ore_crusted_chitin', 'biomeLeaving' => 'shale_grit', 'description' => 'Grew a seam through itself standing over one. Nothing has taken a hex off it yet.'],
        'slagjaw' => ['name' => 'Slagjaw', 'biome' => 'badlands', 'tier' => 1, 'level' => 5, 'profile' => 'brute', 'attack' => 1200, 'defense' => 500, 'hp' => 5200, 'wearBias' => 1.0, 'gold' => [5, 10], 'plate' => 'cracked_carapace', 'ichor' => 'thin_ichor', 'rareSpoil' => 'bone_plate', 'biomeSpoil' => 'slagged_scale', 'biomeLeaving' => 'scorched_grit', 'description' => 'Chews the crust for what is under it and will chew you for the same reason.'],
        'ashcrust_grub' => ['name' => 'Ashcrust Grub', 'biome' => 'badlands', 'tier' => 1, 'level' => 1, 'profile' => 'carapace', 'attack' => 600, 'defense' => 1100, 'hp' => 4000, 'wearBias' => 1.0, 'gold' => [5, 10], 'plate' => 'cracked_carapace', 'ichor' => 'thin_ichor', 'rareSpoil' => 'bone_plate', 'biomeSpoil' => 'slagged_scale', 'biomeLeaving' => 'scorched_grit', 'description' => 'Bakes a shell out of the flat it lies on. You will step on it before you see it.'],
        'cinder_lash' => ['name' => 'Cinder Lash', 'biome' => 'badlands', 'tier' => 2, 'level' => 11, 'profile' => 'swift', 'attack' => 2100, 'defense' => 1900, 'hp' => 10500, 'wearBias' => 1.4, 'gold' => [15, 28], 'plate' => 'bone_plate', 'ichor' => 'black_blood', 'rareSpoil' => 'scaled_hide', 'biomeSpoil' => 'slagged_scale', 'biomeLeaving' => 'scorched_grit', 'description' => 'Whips out of a vent, opens a seam in whatever it touches, and is gone.'],
        'kiln_tortoise' => ['name' => 'Kiln Tortoise', 'biome' => 'badlands', 'tier' => 3, 'level' => 20, 'profile' => 'carapace', 'attack' => 1800, 'defense' => 3800, 'hp' => 14400, 'wearBias' => 1.0, 'gold' => [33, 58], 'plate' => 'scaled_hide', 'ichor' => 'bile_sac', 'rareSpoil' => 'warped_barb', 'biomeSpoil' => 'slagged_scale', 'biomeLeaving' => 'scorched_grit', 'description' => 'Bakes itself hard in the vents and takes all afternoon to get through.'],
        'ash_revenant' => ['name' => 'Ash Revenant', 'biome' => 'badlands', 'tier' => 4, 'level' => 49, 'profile' => 'brute', 'attack' => 6000, 'defense' => 3000, 'hp' => 27600, 'wearBias' => 1.0, 'gold' => [66, 115], 'plate' => 'warped_barb', 'ichor' => 'ember_gland', 'rareSpoil' => 'revenant_plate', 'biomeSpoil' => 'slagged_scale', 'biomeLeaving' => 'scorched_grit', 'description' => 'Walked out of the center with the fire still on it and has not stopped since.'],
        'ditch_crawler' => ['name' => 'Ditch Crawler', 'biome' => 'grassland', 'tier' => 1, 'level' => 1, 'profile' => 'carapace', 'attack' => 600, 'defense' => 1100, 'hp' => 4000, 'wearBias' => 1.0, 'gold' => [5, 10], 'plate' => 'cracked_carapace', 'ichor' => 'thin_ichor', 'rareSpoil' => 'bone_plate', 'biomeSpoil' => 'pollen_choked_gill', 'biomeLeaving' => 'broken_stalks', 'description' => 'Sits in the wheel rut with its back plated over and waits to be stepped on.'],
        'fen_boar' => ['name' => 'Fen Boar', 'biome' => 'grassland', 'tier' => 1, 'level' => 5, 'profile' => 'brute', 'attack' => 1200, 'defense' => 500, 'hp' => 5200, 'wearBias' => 1.0, 'gold' => [5, 10], 'plate' => 'cracked_carapace', 'ichor' => 'thin_ichor', 'rareSpoil' => 'bone_plate', 'biomeSpoil' => 'pollen_choked_gill', 'biomeLeaving' => 'broken_stalks', 'description' => 'Comes out of the reeds at the shins and is through you before it is seen.'],
        'reed_lurker' => ['name' => 'Reed Lurker', 'biome' => 'grassland', 'tier' => 2, 'level' => 11, 'profile' => 'swift', 'attack' => 2100, 'defense' => 1900, 'hp' => 10500, 'wearBias' => 1.4, 'gold' => [15, 28], 'plate' => 'bone_plate', 'ichor' => 'black_blood', 'rareSpoil' => 'scaled_hide', 'biomeSpoil' => 'pollen_choked_gill', 'biomeLeaving' => 'broken_stalks', 'description' => 'Stands still in the tall grass until the grass beside it is what moves.'],
        'tallgrass_prowler' => ['name' => 'Tallgrass Prowler', 'biome' => 'grassland', 'tier' => 3, 'level' => 29, 'profile' => 'brute', 'attack' => 3600, 'defense' => 1700, 'hp' => 18400, 'wearBias' => 1.0, 'gold' => [33, 58], 'plate' => 'scaled_hide', 'ichor' => 'bile_sac', 'rareSpoil' => 'warped_barb', 'biomeSpoil' => 'pollen_choked_gill', 'biomeLeaving' => 'broken_stalks', 'description' => 'You will hear the seed heads part and nothing else until it is on the hex.'],
        'barrow_knight' => ['name' => 'Barrow Knight', 'biome' => 'grassland', 'tier' => 4, 'level' => 38, 'profile' => 'carapace', 'attack' => 3200, 'defense' => 5800, 'hp' => 21600, 'wearBias' => 1.0, 'gold' => [66, 115], 'plate' => 'warped_barb', 'ichor' => 'ember_gland', 'rareSpoil' => 'revenant_plate', 'biomeSpoil' => 'pollen_choked_gill', 'biomeLeaving' => 'broken_stalks', 'description' => 'Whatever it was buried in, it is still wearing. Nothing gets through the front.'],
    ];

    /**
     * §9.5.2 -- what stands on each country, ring by ring.
     *
     * The BIOME decides which five you can meet at all and the RING
     * decides which of them are out: its own tier and the one outside
     * it, so walking inward you meet one you know and one you do not.
     * The rim carries both of its tier ones, because a first country
     * should not be a single creature repeated.
     */
    public const BY_BIOME_RING = [
        'forest' => [
            'outer' => ['moss_hound', 'thicket_darter'],
            'mid' => ['moss_hound', 'thicket_darter', 'thornback'],
            'inner' => ['thornback', 'rootbound_elder'],
            'center' => ['rootbound_elder', 'pale_stalker'],
        ],
        'mountain' => [
            'outer' => ['pick_scarred_ram', 'talus_creeper'],
            'mid' => ['pick_scarred_ram', 'talus_creeper', 'slag_ogre'],
            'inner' => ['slag_ogre', 'ridge_wyrm'],
            'center' => ['ridge_wyrm', 'mythril_warden'],
        ],
        'badlands' => [
            'outer' => ['slagjaw', 'ashcrust_grub'],
            'mid' => ['slagjaw', 'ashcrust_grub', 'cinder_lash'],
            'inner' => ['cinder_lash', 'kiln_tortoise'],
            'center' => ['kiln_tortoise', 'ash_revenant'],
        ],
        'grassland' => [
            'outer' => ['ditch_crawler', 'fen_boar'],
            'mid' => ['ditch_crawler', 'fen_boar', 'reed_lurker'],
            'inner' => ['reed_lurker', 'tallgrass_prowler'],
            'center' => ['tallgrass_prowler', 'barrow_knight'],
        ],
    ];
}
