<?php

declare(strict_types=1);

namespace App\Game;

/**
 * §7.4 -- the skills a job teaches, and the ranks each one climbs.
 *
 * Generated by `php scripts/gen_skills.php` -- do not edit by hand.
 *
 * A job used to be thirty separate nodes drawn as a diagram, and the thirty
 * were never thirty ideas: they were a handful of effects repeated under
 * different names. Explorer's fifteen were two -- straps thirteen times and
 * sight twice -- and Deep Pockets, Second Strap, Rolled Blanket, Even Load,
 * Side Pouch, Bindle, Sorted Kit, Tump Line, Packer's Knot, Outer Pockets and
 * Long Haul were eleven different words for the same +2.
 *
 * So a skill is ONE entry with ranks, and 495 nodes are 95 skills.
 *
 * **A rank IS a node.** Every rank names one of Jobs::NODES, which stays the
 * effect ledger -- so every value, every level gate and every cap in Balance is
 * exactly what it was and the balance of the game has not moved by a point.
 * What changed is how many things a player is asked to read.
 *
 * **Rank order is the prerequisite.** Rank 3 needs rank 2 by being rank 3,
 * which is what a ladder means, so `requires` is no longer read anywhere. That
 * costs the forks §7.4.2 argued for -- a capstone naming two parents is gone --
 * and it is the trade the shape makes: what a tree bought with its branching
 * was a shape to plan, and what it cost was thirty rows nobody could hold in
 * their head.
 *
 * **A battle skill is a one-rank skill** (§9.5.9): owning it is the whole
 * effect, so Onslaught, Sunder and Riposte are three entries rather than three
 * ranks of one, and they sit in the same list as the levelled ones.
 */
final class Skills
{
    /**
     * Keyed by skill. `ranks` are ordered by the level that opens them, and
     * each names the Jobs::NODES row that carries its effect.
     *
     * @var array<string,array<string,mixed>>
     */
    public const ALL = [
        'sawyer.presence' => [
            'job' => 'sawyer',
            'kind' => 'presence',
            'name' => 'Attendance',
            'description' => 'Worth more for standing at the bench while it works.',
            'ranks' => [
                ['node' => 'sawyer.drying_stack', 'level' => 1],
                ['node' => 'sawyer.pit_rhythm', 'level' => 5],
                ['node' => 'sawyer.seasoning_shed', 'level' => 12],
                ['node' => 'sawyer.two_man_tempo', 'level' => 12],
                ['node' => 'sawyer.blade_tension', 'level' => 12],
                ['node' => 'sawyer.kiln_drying', 'level' => 20],
                ['node' => 'sawyer.pit_crew', 'level' => 20],
                ['node' => 'sawyer.ironwood_setting', 'level' => 20],
            ],
        ],
        'smelter.presence' => [
            'job' => 'smelter',
            'kind' => 'presence',
            'name' => 'Attendance',
            'description' => 'Worth more for standing at the bench while it works.',
            'ranks' => [
                ['node' => 'smelter.roasting_bed', 'level' => 1],
                ['node' => 'smelter.slag_tap', 'level' => 5],
                ['node' => 'smelter.stack_height', 'level' => 5],
                ['node' => 'smelter.hearth_lining', 'level' => 12],
                ['node' => 'smelter.continuous_run', 'level' => 12],
                ['node' => 'smelter.blast_timing', 'level' => 12],
                ['node' => 'smelter.full_burden', 'level' => 20],
                ['node' => 'smelter.water_bellows', 'level' => 20],
                ['node' => 'smelter.mythril_heat', 'level' => 20],
            ],
        ],
        'tanner.presence' => [
            'job' => 'tanner',
            'kind' => 'presence',
            'name' => 'Attendance',
            'description' => 'Worth more for standing at the bench while it works.',
            'ranks' => [
                ['node' => 'tanner.salt_cure', 'level' => 1],
                ['node' => 'tanner.lime_pit', 'level' => 1],
                ['node' => 'tanner.drying_loft', 'level' => 1],
                ['node' => 'tanner.pit_rotation', 'level' => 5],
                ['node' => 'tanner.bating', 'level' => 5],
                ['node' => 'tanner.oak_and_hemlock', 'level' => 5],
                ['node' => 'tanner.oil_tannage', 'level' => 12],
                ['node' => 'tanner.alum_tawing', 'level' => 12],
                ['node' => 'tanner.steady_warmth', 'level' => 12],
                ['node' => 'tanner.split_hides', 'level' => 12],
                ['node' => 'tanner.chamois_work', 'level' => 20],
                ['node' => 'tanner.hardened_leather', 'level' => 20],
                ['node' => 'tanner.beastfang_curing', 'level' => 20],
            ],
        ],
        'mason.presence' => [
            'job' => 'mason',
            'kind' => 'presence',
            'name' => 'Attendance',
            'description' => 'Worth more for standing at the bench while it works.',
            'ranks' => [
                ['node' => 'mason.dressing_shed', 'level' => 1],
                ['node' => 'mason.mallet_rhythm', 'level' => 5],
                ['node' => 'mason.limestone_and_grit', 'level' => 5],
                ['node' => 'mason.ashlar_course', 'level' => 12],
                ['node' => 'mason.molded_work', 'level' => 12],
                ['node' => 'mason.wet_cutting', 'level' => 12],
                ['node' => 'mason.frost_stone', 'level' => 12],
                ['node' => 'mason.voussoir_cutting', 'level' => 20],
                ['node' => 'mason.carved_work', 'level' => 20],
            ],
        ],
        'weaver.presence' => [
            'job' => 'weaver',
            'kind' => 'presence',
            'name' => 'Attendance',
            'description' => 'Worth more for standing at the bench while it works.',
            'ranks' => [
                ['node' => 'weaver.retting_judgment', 'level' => 1],
                ['node' => 'weaver.warping_board', 'level' => 5],
                ['node' => 'weaver.broad_loom', 'level' => 5],
                ['node' => 'weaver.fulling_trough', 'level' => 12],
                ['node' => 'weaver.twill_setting', 'level' => 12],
                ['node' => 'weaver.damp_weaving', 'level' => 12],
                ['node' => 'weaver.napping_teasels', 'level' => 20],
                ['node' => 'weaver.figured_weave', 'level' => 20],
                ['node' => 'weaver.silkweave_handling', 'level' => 20],
            ],
        ],
        'woodcutting.bite' => [
            'job' => 'woodcutting',
            'kind' => 'bite',
            'name' => 'Bite',
            'description' => 'Attack against the hex, on this line only.',
            'ranks' => [
                ['node' => 'woodcutting.swing_economy', 'level' => 1],
                ['node' => 'woodcutting.bucking_rhythm', 'level' => 5],
                ['node' => 'woodcutting.kerf_control', 'level' => 12],
                ['node' => 'woodcutting.felling_line', 'level' => 20],
            ],
        ],
        'mining.bite' => [
            'job' => 'mining',
            'kind' => 'bite',
            'name' => 'Bite',
            'description' => 'Attack against the hex, on this line only.',
            'ranks' => [
                ['node' => 'mining.drive_rhythm', 'level' => 1],
                ['node' => 'mining.double_jack', 'level' => 5],
                ['node' => 'mining.face_lighting', 'level' => 12],
                ['node' => 'mining.shift_pacing', 'level' => 20],
            ],
        ],
        'hunting.bite' => [
            'job' => 'hunting',
            'kind' => 'bite',
            'name' => 'Bite',
            'description' => 'Attack against the hex, on this line only.',
            'ranks' => [
                ['node' => 'hunting.wind_reading', 'level' => 1],
                ['node' => 'hunting.short_stalk', 'level' => 5],
                ['node' => 'hunting.call_work', 'level' => 12],
                ['node' => 'hunting.skinning_speed', 'level' => 20],
            ],
        ],
        'quarrying.bite' => [
            'job' => 'quarrying',
            'kind' => 'bite',
            'name' => 'Bite',
            'description' => 'Attack against the hex, on this line only.',
            'ranks' => [
                ['node' => 'quarrying.hammer_angle', 'level' => 1],
                ['node' => 'quarrying.sledge_relay', 'level' => 5],
                ['node' => 'quarrying.bench_pacing', 'level' => 12],
                ['node' => 'quarrying.dry_season_work', 'level' => 20],
            ],
        ],
        'harvesting.bite' => [
            'job' => 'harvesting',
            'kind' => 'bite',
            'name' => 'Bite',
            'description' => 'Attack against the hex, on this line only.',
            'ranks' => [
                ['node' => 'harvesting.hook_angle', 'level' => 1],
                ['node' => 'harvesting.scythe_stance', 'level' => 5],
                ['node' => 'harvesting.steady_pace', 'level' => 12],
                ['node' => 'harvesting.cool_hours', 'level' => 20],
            ],
        ],
        'alchemist.stat' => [
            'job' => 'alchemist',
            'kind' => 'stat',
            'name' => 'Brewing Speed',
            'description' => 'A faster hour at the consumable bench.',
            'ranks' => [
                ['node' => 'alchemist.clean_glass', 'level' => 1],
                ['node' => 'alchemist.cold_steep', 'level' => 1],
                ['node' => 'alchemist.double_boiler', 'level' => 5],
                ['node' => 'alchemist.warm_room', 'level' => 5],
                ['node' => 'alchemist.slow_infusion', 'level' => 12],
                ['node' => 'alchemist.bench_order', 'level' => 12],
                ['node' => 'alchemist.bitter_tincture', 'level' => 20],
                ['node' => 'alchemist.the_house_blend', 'level' => 28],
                ['node' => 'alchemist.capital_supplier', 'level' => 28],
            ],
        ],
        'alchemist.stackCap' => [
            'job' => 'alchemist',
            'kind' => 'stackCap',
            'name' => 'Cellar',
            'description' => 'A deeper shelf for each draft carried.',
            'ranks' => [
                ['node' => 'alchemist.sealed_stopper', 'level' => 1],
                ['node' => 'alchemist.wax_seal', 'level' => 5],
                ['node' => 'alchemist.mineral_mordant', 'level' => 12],
                ['node' => 'alchemist.deep_reserve', 'level' => 20],
                ['node' => 'alchemist.kiln_dried_stock', 'level' => 20],
                ['node' => 'alchemist.shelf_life', 'level' => 20],
            ],
        ],
        'mason.stat' => [
            'job' => 'mason',
            'kind' => 'stat',
            'name' => 'Chisel Speed',
            'description' => 'A faster run at a masonry.',
            'ranks' => [
                ['node' => 'mason.banker_bench', 'level' => 1],
                ['node' => 'mason.mark_and_measure', 'level' => 1],
                ['node' => 'mason.punch_work', 'level' => 1],
                ['node' => 'mason.chisel_angle', 'level' => 1],
                ['node' => 'mason.claw_and_boaster', 'level' => 5],
                ['node' => 'mason.sand_saw', 'level' => 5],
                ['node' => 'mason.true_arris', 'level' => 12],
                ['node' => 'mason.drafted_margin', 'level' => 12],
                ['node' => 'mason.final_rub', 'level' => 20],
                ['node' => 'mason.setting_out_floor', 'level' => 20],
            ],
        ],
        'runecaster.ember_bolt' => [
            'job' => 'runecaster',
            'kind' => 'battleSkill',
            'name' => 'Ember Bolt',
            'description' => 'One of the three a Runecaster carries into a fight.',
            'ranks' => [
                ['node' => 'runecaster.ember_bolt', 'level' => 1],
            ],
        ],
        'alchemist.brewExtra' => [
            'job' => 'alchemist',
            'kind' => 'brewExtra',
            'name' => 'Extra Flask',
            'description' => 'Chance of an extra flask off a brew.',
            'ranks' => [
                ['node' => 'alchemist.nose_for_it', 'level' => 1],
                ['node' => 'alchemist.resin_binding', 'level' => 5],
                ['node' => 'alchemist.potency_titration', 'level' => 5],
                ['node' => 'alchemist.sediment_reading', 'level' => 5],
                ['node' => 'alchemist.fractional_draw', 'level' => 12],
                ['node' => 'alchemist.crystal_seeding', 'level' => 12],
                ['node' => 'alchemist.perfect_draft', 'level' => 20],
            ],
        ],
        'hunting.stat' => [
            'job' => 'hunting',
            'kind' => 'stat',
            'name' => 'Field Dressing',
            'description' => 'More off the animal you take.',
            'ranks' => [
                ['node' => 'hunting.quiet_step', 'level' => 1],
                ['node' => 'hunting.game_trail', 'level' => 1],
                ['node' => 'hunting.clean_release', 'level' => 1],
                ['node' => 'hunting.sign_reading', 'level' => 5],
                ['node' => 'hunting.rut_timing', 'level' => 5],
                ['node' => 'hunting.high_pasture', 'level' => 5],
                ['node' => 'hunting.vital_shot', 'level' => 12],
                ['node' => 'hunting.bone_and_sinew', 'level' => 12],
                ['node' => 'hunting.dawn_watch', 'level' => 20],
                ['node' => 'hunting.tallow_rendering', 'level' => 20],
            ],
        ],
        'armorer.stat' => [
            'job' => 'armorer',
            'kind' => 'stat',
            'name' => 'Fitting Speed',
            'description' => 'A faster hour at the armor bench.',
            'ranks' => [
                ['node' => 'armorer.measured_cut', 'level' => 1],
                ['node' => 'armorer.boot_last', 'level' => 1],
                ['node' => 'armorer.sole_stitching', 'level' => 12],
                ['node' => 'armorer.breathable_lining', 'level' => 12],
                ['node' => 'armorer.bulk_tanning', 'level' => 12],
                ['node' => 'armorer.road_sole', 'level' => 20],
                ['node' => 'armorer.gusset_work', 'level' => 20],
                ['node' => 'armorer.outfitter_of_the_ring', 'level' => 28],
            ],
        ],
        'smith.stat' => [
            'job' => 'smith',
            'kind' => 'stat',
            'name' => 'Forge Speed',
            'description' => 'A faster hour at the weapon bench.',
            'ranks' => [
                ['node' => 'smith.whetstone_round', 'level' => 1],
                ['node' => 'smith.bellows_rhythm', 'level' => 1],
                ['node' => 'smith.twin_stroke', 'level' => 5],
                ['node' => 'smith.hollow_grind', 'level' => 12],
                ['node' => 'smith.striker_pair', 'level' => 12],
                ['node' => 'smith.hearth_discipline', 'level' => 20],
                ['node' => 'smith.tang_extension', 'level' => 20],
                ['node' => 'smith.scale_hammering', 'level' => 20],
            ],
        ],
        'smelter.stat' => [
            'job' => 'smelter',
            'kind' => 'stat',
            'name' => 'Furnace Draft',
            'description' => 'A faster run at a furnace.',
            'ranks' => [
                ['node' => 'smelter.bloomery', 'level' => 1],
                ['node' => 'smelter.charge_order', 'level' => 1],
                ['node' => 'smelter.tuyere_angle', 'level' => 1],
                ['node' => 'smelter.bellows_pair', 'level' => 5],
                ['node' => 'smelter.preheated_blast', 'level' => 5],
                ['node' => 'smelter.finery_forge', 'level' => 12],
                ['node' => 'smelter.banded_frame', 'level' => 12],
                ['node' => 'smelter.crucible_melt', 'level' => 20],
                ['node' => 'smelter.alloying', 'level' => 20],
            ],
        ],
        'shieldbearer.pair' => [
            'job' => 'shieldbearer',
            'kind' => 'pair',
            'name' => 'Guard and Edge',
            'description' => 'Solid points of attack and defense.',
            'ranks' => [
                ['node' => 'shieldbearer.braced_stance', 'level' => 1],
                ['node' => 'shieldbearer.rim_work', 'level' => 1],
                ['node' => 'shieldbearer.shoulder_behind', 'level' => 1],
                ['node' => 'shieldbearer.boss_punch', 'level' => 1],
                ['node' => 'shieldbearer.angled_deflection', 'level' => 5],
                ['node' => 'shieldbearer.low_guard', 'level' => 5],
                ['node' => 'shieldbearer.recovery_step', 'level' => 5],
                ['node' => 'shieldbearer.breath_control', 'level' => 5],
                ['node' => 'shieldbearer.overlap_cover', 'level' => 12],
                ['node' => 'shieldbearer.counter_shove', 'level' => 12],
                ['node' => 'shieldbearer.edge_catch', 'level' => 12],
                ['node' => 'shieldbearer.unmoved', 'level' => 12],
                ['node' => 'shieldbearer.boss_reseat', 'level' => 20],
                ['node' => 'shieldbearer.glancing_habit', 'level' => 20],
            ],
        ],
        'swordhand.pair' => [
            'job' => 'swordhand',
            'kind' => 'pair',
            'name' => 'Guard and Edge',
            'description' => 'Solid points of attack and defense.',
            'ranks' => [
                ['node' => 'swordhand.true_grip', 'level' => 1],
                ['node' => 'swordhand.half_step', 'level' => 1],
                ['node' => 'swordhand.wrist_cut', 'level' => 1],
                ['node' => 'swordhand.guard_change', 'level' => 1],
                ['node' => 'swordhand.off_hand_check', 'level' => 5],
                ['node' => 'swordhand.rising_cut', 'level' => 5],
                ['node' => 'swordhand.footwork_drill', 'level' => 5],
                ['node' => 'swordhand.point_control', 'level' => 5],
                ['node' => 'swordhand.long_guard', 'level' => 12],
                ['node' => 'swordhand.reading_stance', 'level' => 12],
                ['node' => 'swordhand.economy_of_motion', 'level' => 12],
                ['node' => 'swordhand.flat_of_the_blade', 'level' => 20],
                ['node' => 'swordhand.no_wasted_swing', 'level' => 20],
            ],
        ],
        'runecaster.pair' => [
            'job' => 'runecaster',
            'kind' => 'pair',
            'name' => 'Guard and Edge',
            'description' => 'Solid points of attack and defense.',
            'ranks' => [
                ['node' => 'runecaster.cut_sigil', 'level' => 1],
                ['node' => 'runecaster.ore_ink', 'level' => 1],
                ['node' => 'runecaster.breath_line', 'level' => 1],
                ['node' => 'runecaster.layered_mark', 'level' => 5],
                ['node' => 'runecaster.resonance', 'level' => 5],
                ['node' => 'runecaster.sight_beyond', 'level' => 5],
                ['node' => 'runecaster.null_stroke', 'level' => 5],
                ['node' => 'runecaster.warding_ring', 'level' => 12],
                ['node' => 'runecaster.silence_before', 'level' => 12],
                ['node' => 'runecaster.long_burn', 'level' => 12],
                ['node' => 'runecaster.measured_draw', 'level' => 20],
                ['node' => 'runecaster.rest_the_rod', 'level' => 20],
                ['node' => 'runecaster.clean_the_groove', 'level' => 20],
            ],
        ],
        'shieldbearer.battleWear' => [
            'job' => 'shieldbearer',
            'kind' => 'battleWear',
            'name' => 'Kit Care',
            'description' => 'A share of what a fight takes off the worn kit, spared.',
            'ranks' => [
                ['node' => 'shieldbearer.short_steps', 'level' => 1],
                ['node' => 'shieldbearer.strap_discipline', 'level' => 5],
                ['node' => 'shieldbearer.field_repair', 'level' => 12],
                ['node' => 'shieldbearer.rim_binding', 'level' => 20],
                ['node' => 'shieldbearer.board_swap', 'level' => 20],
            ],
        ],
        'swordhand.battleWear' => [
            'job' => 'swordhand',
            'kind' => 'battleWear',
            'name' => 'Kit Care',
            'description' => 'A share of what a fight takes off the worn kit, spared.',
            'ranks' => [
                ['node' => 'swordhand.bind_and_slip', 'level' => 1],
                ['node' => 'swordhand.scabbard_fit', 'level' => 20],
                ['node' => 'swordhand.pommel_seat', 'level' => 28],
            ],
        ],
        'runecaster.battleWear' => [
            'job' => 'runecaster',
            'kind' => 'battleWear',
            'name' => 'Kit Care',
            'description' => 'A share of what a fight takes off the worn kit, spared.',
            'ranks' => [
                ['node' => 'runecaster.grounding_rod', 'level' => 1],
            ],
        ],
        'weaver.stat' => [
            'job' => 'weaver',
            'kind' => 'stat',
            'name' => 'Loom Speed',
            'description' => 'A faster run at a loom.',
            'ranks' => [
                ['node' => 'weaver.the_brake', 'level' => 1],
                ['node' => 'weaver.scutching_blade', 'level' => 1],
                ['node' => 'weaver.distaff_dressing', 'level' => 1],
                ['node' => 'weaver.treadle_wheel', 'level' => 5],
                ['node' => 'weaver.even_tension', 'level' => 5],
                ['node' => 'weaver.shed_and_pick', 'level' => 12],
                ['node' => 'weaver.flying_shuttle', 'level' => 12],
                ['node' => 'weaver.off_the_loom', 'level' => 20],
                ['node' => 'weaver.loom_discipline', 'level' => 20],
            ],
        ],
        'smith.craftOption' => [
            'job' => 'smith',
            'kind' => 'craftOption',
            'name' => 'Maker\'s Luck',
            'description' => 'Chance of an extra rolled line on what you make.',
            'ranks' => [
                ['node' => 'smith.hammer_sense', 'level' => 1],
                ['node' => 'smith.billet_folding', 'level' => 5],
                ['node' => 'smith.crucible_steel', 'level' => 12],
                ['node' => 'smith.mastersmith_eye', 'level' => 20],
            ],
        ],
        'armorer.craftOption' => [
            'job' => 'armorer',
            'kind' => 'craftOption',
            'name' => 'Maker\'s Luck',
            'description' => 'Chance of an extra rolled line on what you make.',
            'ranks' => [
                ['node' => 'armorer.fit_by_eye', 'level' => 1],
                ['node' => 'armorer.padded_arming', 'level' => 5],
                ['node' => 'armorer.lamellar_lacing', 'level' => 12],
            ],
        ],
        'swordhand.onslaught' => [
            'job' => 'swordhand',
            'kind' => 'battleSkill',
            'name' => 'Onslaught',
            'description' => 'One of the three a Swordhand carries into a fight.',
            'ranks' => [
                ['node' => 'swordhand.onslaught', 'level' => 1],
            ],
        ],
        'mining.stat' => [
            'job' => 'mining',
            'kind' => 'stat',
            'name' => 'Ore Sense',
            'description' => 'A bigger haul off a mountain seam.',
            'ranks' => [
                ['node' => 'mining.seam_reading', 'level' => 1],
                ['node' => 'mining.face_squaring', 'level' => 1],
                ['node' => 'mining.ore_sorting', 'level' => 5],
                ['node' => 'mining.tally_stick', 'level' => 5],
                ['node' => 'mining.bucket_line', 'level' => 5],
                ['node' => 'mining.vein_following', 'level' => 12],
                ['node' => 'mining.fines_recovery', 'level' => 12],
                ['node' => 'mining.windlass', 'level' => 12],
                ['node' => 'mining.mythril_trace', 'level' => 12],
                ['node' => 'mining.assay_eye', 'level' => 20],
            ],
        ],
        'tanner.stat' => [
            'job' => 'tanner',
            'kind' => 'stat',
            'name' => 'Pit Speed',
            'description' => 'A faster run at a tannery.',
            'ranks' => [
                ['node' => 'tanner.fleshing_beam', 'level' => 1],
                ['node' => 'tanner.scudding', 'level' => 1],
                ['node' => 'tanner.even_immersion', 'level' => 5],
                ['node' => 'tanner.warm_liquor', 'level' => 5],
                ['node' => 'tanner.currying_table', 'level' => 12],
                ['node' => 'tanner.staking', 'level' => 12],
                ['node' => 'tanner.finish_coat', 'level' => 20],
                ['node' => 'tanner.drum_tanning', 'level' => 20],
            ],
        ],
        'harvesting.stat' => [
            'job' => 'harvesting',
            'kind' => 'stat',
            'name' => 'Reaping',
            'description' => 'A bigger haul off a grassland hex.',
            'ranks' => [
                ['node' => 'harvesting.sweep_and_gather', 'level' => 1],
                ['node' => 'harvesting.field_edge', 'level' => 1],
                ['node' => 'harvesting.stalk_selection', 'level' => 1],
                ['node' => 'harvesting.retting_pit', 'level' => 5],
                ['node' => 'harvesting.dew_cutting', 'level' => 5],
                ['node' => 'harvesting.sheaf_stacking', 'level' => 5],
                ['node' => 'harvesting.long_fiber', 'level' => 12],
                ['node' => 'harvesting.chaff_reclaim', 'level' => 12],
                ['node' => 'harvesting.combing_board', 'level' => 20],
                ['node' => 'harvesting.second_cut', 'level' => 20],
            ],
        ],
        'sawyer.stat' => [
            'job' => 'sawyer',
            'kind' => 'stat',
            'name' => 'Saw Speed',
            'description' => 'A faster run at a saw pit.',
            'ranks' => [
                ['node' => 'sawyer.saw_set', 'level' => 1],
                ['node' => 'sawyer.sawpit', 'level' => 1],
                ['node' => 'sawyer.steady_stroke', 'level' => 1],
                ['node' => 'sawyer.kerf_line', 'level' => 5],
                ['node' => 'sawyer.frame_saw', 'level' => 5],
                ['node' => 'sawyer.roller_bed', 'level' => 5],
                ['node' => 'sawyer.sharpening_round', 'level' => 12],
                ['node' => 'sawyer.quarter_sawn', 'level' => 12],
                ['node' => 'sawyer.true_planing', 'level' => 20],
                ['node' => 'sawyer.laminated_stock', 'level' => 20],
            ],
        ],
        'woodcutting.seamGrade' => [
            'job' => 'woodcutting',
            'kind' => 'seamGrade',
            'name' => 'Seam Eye',
            'description' => 'Mines that come up a grade past what the tool reliably takes.',
            'ranks' => [
                ['node' => 'woodcutting.coppice_stand', 'level' => 1],
                ['node' => 'woodcutting.windfall_sense', 'level' => 5],
                ['node' => 'woodcutting.old_growth', 'level' => 5],
                ['node' => 'woodcutting.sheltered_draw', 'level' => 12],
                ['node' => 'woodcutting.burnt_stand', 'level' => 12],
                ['node' => 'woodcutting.river_stand', 'level' => 12],
                ['node' => 'woodcutting.the_marked_grove', 'level' => 28],
            ],
        ],
        'mining.seamGrade' => [
            'job' => 'mining',
            'kind' => 'seamGrade',
            'name' => 'Seam Eye',
            'description' => 'Mines that come up a grade past what the tool reliably takes.',
            'ranks' => [
                ['node' => 'mining.outcrop_break', 'level' => 1],
                ['node' => 'mining.shallow_adit', 'level' => 1],
                ['node' => 'mining.prop_setting', 'level' => 5],
                ['node' => 'mining.deep_drift', 'level' => 5],
                ['node' => 'mining.flooded_level', 'level' => 12],
                ['node' => 'mining.deep_shaft_right', 'level' => 20],
                ['node' => 'mining.the_named_seam', 'level' => 28],
            ],
        ],
        'hunting.seamGrade' => [
            'job' => 'hunting',
            'kind' => 'seamGrade',
            'name' => 'Seam Eye',
            'description' => 'Mines that come up a grade past what the tool reliably takes.',
            'ranks' => [
                ['node' => 'hunting.herd_ground', 'level' => 1],
                ['node' => 'hunting.marsh_edge', 'level' => 12],
                ['node' => 'hunting.salt_lick', 'level' => 12],
                ['node' => 'hunting.beast_run', 'level' => 12],
                ['node' => 'hunting.winter_yard', 'level' => 20],
                ['node' => 'hunting.beastfang_ground', 'level' => 20],
            ],
        ],
        'quarrying.seamGrade' => [
            'job' => 'quarrying',
            'kind' => 'seamGrade',
            'name' => 'Seam Eye',
            'description' => 'Mines that come up a grade past what the tool reliably takes.',
            'ranks' => [
                ['node' => 'quarrying.shelf_quarry', 'level' => 1],
                ['node' => 'quarrying.frost_splitting', 'level' => 5],
                ['node' => 'quarrying.deep_bench', 'level' => 5],
                ['node' => 'quarrying.crack_reading', 'level' => 12],
                ['node' => 'quarrying.canyon_face', 'level' => 12],
                ['node' => 'quarrying.deep_badland', 'level' => 20],
                ['node' => 'quarrying.the_great_bench', 'level' => 28],
            ],
        ],
        'harvesting.seamGrade' => [
            'job' => 'harvesting',
            'kind' => 'seamGrade',
            'name' => 'Seam Eye',
            'description' => 'Mines that come up a grade past what the tool reliably takes.',
            'ranks' => [
                ['node' => 'harvesting.fallow_strip', 'level' => 1],
                ['node' => 'harvesting.river_meadow', 'level' => 5],
                ['node' => 'harvesting.seed_saving', 'level' => 5],
                ['node' => 'harvesting.silk_ground', 'level' => 12],
                ['node' => 'harvesting.storm_meadow', 'level' => 12],
                ['node' => 'harvesting.silkweave_run', 'level' => 20],
                ['node' => 'harvesting.the_long_field', 'level' => 28],
            ],
        ],
        'shieldbearer.shield_bash' => [
            'job' => 'shieldbearer',
            'kind' => 'battleSkill',
            'name' => 'Shield Bash',
            'description' => 'One of the three a Shieldbearer carries into a fight.',
            'ranks' => [
                ['node' => 'shieldbearer.shield_bash', 'level' => 1],
            ],
        ],
        'runecaster.skillPower' => [
            'job' => 'runecaster',
            'kind' => 'skillPower',
            'name' => 'Skill Power',
            'description' => 'More of the extra on your family\'s three skills.',
            'ranks' => [
                ['node' => 'runecaster.ember_draw', 'level' => 1],
                ['node' => 'runecaster.overdraw', 'level' => 20],
                ['node' => 'runecaster.unspent_charge', 'level' => 20],
            ],
        ],
        'quarrying.stat' => [
            'job' => 'quarrying',
            'kind' => 'stat',
            'name' => 'Stonecutting',
            'description' => 'A bigger haul off badlands stone.',
            'ranks' => [
                ['node' => 'quarrying.bedding_plane', 'level' => 1],
                ['node' => 'quarrying.block_marking', 'level' => 1],
                ['node' => 'quarrying.dressing_cuts', 'level' => 5],
                ['node' => 'quarrying.spoil_sorting', 'level' => 5],
                ['node' => 'quarrying.true_face', 'level' => 12],
                ['node' => 'quarrying.offcut_dressing', 'level' => 12],
                ['node' => 'quarrying.facing_stone', 'level' => 20],
                ['node' => 'quarrying.rubble_reclaim', 'level' => 20],
            ],
        ],
        'smith.craftDurability' => [
            'job' => 'smith',
            'kind' => 'craftDurability',
            'name' => 'Temper',
            'description' => 'Higher starting durability on what you make.',
            'ranks' => [
                ['node' => 'smith.dry_seated_haft', 'level' => 1],
                ['node' => 'smith.drawn_temper', 'level' => 5],
                ['node' => 'smith.quench_oil', 'level' => 5],
                ['node' => 'smith.shoulder_fit', 'level' => 5],
                ['node' => 'smith.differential_temper', 'level' => 12],
                ['node' => 'smith.socket_and_wedge', 'level' => 20],
                ['node' => 'smith.the_named_blade', 'level' => 28],
            ],
        ],
        'armorer.craftDurability' => [
            'job' => 'armorer',
            'kind' => 'craftDurability',
            'name' => 'Temper',
            'description' => 'Higher starting durability on what you make.',
            'ranks' => [
                ['node' => 'armorer.doubled_seam', 'level' => 1],
                ['node' => 'armorer.waxed_thread', 'level' => 5],
                ['node' => 'armorer.riveted_lap', 'level' => 5],
                ['node' => 'armorer.flex_panel', 'level' => 5],
                ['node' => 'armorer.hardened_boss', 'level' => 12],
                ['node' => 'armorer.load_transfer', 'level' => 20],
                ['node' => 'armorer.the_second_skin', 'level' => 28],
            ],
        ],
        'sawyer.costReduction' => [
            'job' => 'sawyer',
            'kind' => 'costReduction',
            'name' => 'Thrift',
            'description' => 'Fewer inputs per run.',
            'ranks' => [
                ['node' => 'sawyer.bark_first', 'level' => 1],
                ['node' => 'sawyer.log_dogs', 'level' => 1],
                ['node' => 'sawyer.slab_first', 'level' => 5],
                ['node' => 'sawyer.green_and_dry', 'level' => 5],
                ['node' => 'sawyer.edging_pass', 'level' => 5],
                ['node' => 'sawyer.heart_and_sap', 'level' => 12],
                ['node' => 'sawyer.offcut_shingles', 'level' => 12],
                ['node' => 'sawyer.full_trunk', 'level' => 20],
            ],
        ],
        'smelter.costReduction' => [
            'job' => 'smelter',
            'kind' => 'costReduction',
            'name' => 'Thrift',
            'description' => 'Fewer inputs per run.',
            'ranks' => [
                ['node' => 'smelter.ore_washing', 'level' => 1],
                ['node' => 'smelter.hand_sorting', 'level' => 1],
                ['node' => 'smelter.limestone_flux', 'level' => 5],
                ['node' => 'smelter.charcoal_burn', 'level' => 5],
                ['node' => 'smelter.bloom_squeezing', 'level' => 5],
                ['node' => 'smelter.slag_reclaim', 'level' => 12],
                ['node' => 'smelter.wrought_and_cast', 'level' => 12],
                ['node' => 'smelter.heat_economy', 'level' => 20],
            ],
        ],
        'tanner.costReduction' => [
            'job' => 'tanner',
            'kind' => 'costReduction',
            'name' => 'Thrift',
            'description' => 'Fewer inputs per run.',
            'ranks' => [
                ['node' => 'tanner.bark_liquor', 'level' => 1],
                ['node' => 'tanner.spent_bark', 'level' => 5],
                ['node' => 'tanner.trim_first', 'level' => 5],
                ['node' => 'tanner.offcut_glue', 'level' => 12],
                ['node' => 'tanner.whole_beast', 'level' => 20],
            ],
        ],
        'mason.costReduction' => [
            'job' => 'mason',
            'kind' => 'costReduction',
            'name' => 'Thrift',
            'description' => 'Fewer inputs per run.',
            'ranks' => [
                ['node' => 'mason.template_board', 'level' => 1],
                ['node' => 'mason.bed_and_face', 'level' => 5],
                ['node' => 'mason.sharpening_forge', 'level' => 5],
                ['node' => 'mason.offcut_rubble', 'level' => 5],
                ['node' => 'mason.dust_reclaim', 'level' => 12],
                ['node' => 'mason.block_economy', 'level' => 20],
                ['node' => 'mason.obsidian_dressing', 'level' => 20],
            ],
        ],
        'weaver.costReduction' => [
            'job' => 'weaver',
            'kind' => 'costReduction',
            'name' => 'Thrift',
            'description' => 'Fewer inputs per run.',
            'ranks' => [
                ['node' => 'weaver.sorted_stricks', 'level' => 1],
                ['node' => 'weaver.hackling_combs', 'level' => 1],
                ['node' => 'weaver.tow_and_line', 'level' => 5],
                ['node' => 'weaver.sizing_paste', 'level' => 5],
                ['node' => 'weaver.thrums', 'level' => 5],
                ['node' => 'weaver.noil_carding', 'level' => 12],
                ['node' => 'weaver.nettle_and_flax', 'level' => 12],
                ['node' => 'weaver.whole_stalk', 'level' => 20],
            ],
        ],
        'smith.costReduction' => [
            'job' => 'smith',
            'kind' => 'costReduction',
            'name' => 'Thrift',
            'description' => 'Fewer inputs per run.',
            'ranks' => [
                ['node' => 'smith.cold_shut_eye', 'level' => 1],
                ['node' => 'smith.offcut_ledger', 'level' => 1],
                ['node' => 'smith.charcoal_husbandry', 'level' => 5],
                ['node' => 'smith.forge_economy', 'level' => 12],
                ['node' => 'smith.flux_reading', 'level' => 12],
            ],
        ],
        'armorer.costReduction' => [
            'job' => 'armorer',
            'kind' => 'costReduction',
            'name' => 'Thrift',
            'description' => 'Fewer inputs per run.',
            'ranks' => [
                ['node' => 'armorer.hide_grading', 'level' => 1],
                ['node' => 'armorer.scrap_leather', 'level' => 1],
                ['node' => 'armorer.tannin_economy', 'level' => 5],
                ['node' => 'armorer.paired_cutting', 'level' => 5],
                ['node' => 'armorer.edge_binding', 'level' => 5],
                ['node' => 'armorer.pattern_nesting', 'level' => 12],
                ['node' => 'armorer.hide_yield', 'level' => 12],
                ['node' => 'armorer.ankle_support', 'level' => 20],
            ],
        ],
        'alchemist.costReduction' => [
            'job' => 'alchemist',
            'kind' => 'costReduction',
            'name' => 'Thrift',
            'description' => 'Fewer inputs per run.',
            'ranks' => [
                ['node' => 'alchemist.measured_pour', 'level' => 1],
                ['node' => 'alchemist.spent_mash', 'level' => 1],
                ['node' => 'alchemist.reflux_still', 'level' => 5],
                ['node' => 'alchemist.solvent_recovery', 'level' => 12],
                ['node' => 'alchemist.lees_reclaim', 'level' => 12],
                ['node' => 'alchemist.steady_hand', 'level' => 20],
            ],
        ],
        'woodcutting.toolWear' => [
            'job' => 'woodcutting',
            'kind' => 'toolWear',
            'name' => 'Tool Care',
            'description' => 'Mines that leave the line\'s tool untouched.',
            'ranks' => [
                ['node' => 'woodcutting.two_hand_grip', 'level' => 1],
                ['node' => 'woodcutting.wedge_and_maul', 'level' => 5],
                ['node' => 'woodcutting.helve_care', 'level' => 5],
                ['node' => 'woodcutting.measured_felling', 'level' => 12],
                ['node' => 'woodcutting.stone_and_strop', 'level' => 12],
                ['node' => 'woodcutting.dawn_start', 'level' => 20],
                ['node' => 'woodcutting.bit_guard', 'level' => 20],
                ['node' => 'woodcutting.ironwood_sense', 'level' => 20],
                ['node' => 'woodcutting.woodward', 'level' => 28],
            ],
        ],
        'mining.toolWear' => [
            'job' => 'mining',
            'kind' => 'toolWear',
            'name' => 'Tool Care',
            'description' => 'Mines that leave the line\'s tool untouched.',
            'ranks' => [
                ['node' => 'mining.short_haft_work', 'level' => 1],
                ['node' => 'mining.wedge_lines', 'level' => 5],
                ['node' => 'mining.dry_working', 'level' => 5],
                ['node' => 'mining.helve_soaking', 'level' => 12],
                ['node' => 'mining.cold_chisel', 'level' => 12],
                ['node' => 'mining.gad_and_feather', 'level' => 20],
                ['node' => 'mining.spare_heads', 'level' => 20],
                ['node' => 'mining.roof_bolting', 'level' => 20],
                ['node' => 'mining.shift_captain', 'level' => 28],
            ],
        ],
        'hunting.toolWear' => [
            'job' => 'hunting',
            'kind' => 'toolWear',
            'name' => 'Tool Care',
            'description' => 'Mines that leave the line\'s tool untouched.',
            'ranks' => [
                ['node' => 'hunting.bowstring_wax', 'level' => 1],
                ['node' => 'hunting.nock_check', 'level' => 5],
                ['node' => 'hunting.blind_building', 'level' => 5],
                ['node' => 'hunting.two_shot_draw', 'level' => 5],
                ['node' => 'hunting.limb_rest', 'level' => 5],
                ['node' => 'hunting.spare_string', 'level' => 12],
                ['node' => 'hunting.patience', 'level' => 12],
                ['node' => 'hunting.long_shot', 'level' => 20],
                ['node' => 'hunting.the_quiet_kill', 'level' => 28],
                ['node' => 'hunting.master_of_hounds', 'level' => 28],
            ],
        ],
        'quarrying.toolWear' => [
            'job' => 'quarrying',
            'kind' => 'toolWear',
            'name' => 'Tool Care',
            'description' => 'Mines that leave the line\'s tool untouched.',
            'ranks' => [
                ['node' => 'quarrying.face_sweeping', 'level' => 1],
                ['node' => 'quarrying.shim_work', 'level' => 1],
                ['node' => 'quarrying.handle_seating', 'level' => 5],
                ['node' => 'quarrying.plug_and_feather', 'level' => 5],
                ['node' => 'quarrying.point_dressing', 'level' => 5],
                ['node' => 'quarrying.tempered_iron', 'level' => 12],
                ['node' => 'quarrying.obsidian_flow', 'level' => 12],
                ['node' => 'quarrying.padded_haft', 'level' => 12],
                ['node' => 'quarrying.forge_day', 'level' => 20],
                ['node' => 'quarrying.sound_testing', 'level' => 20],
                ['node' => 'quarrying.quarrymaster', 'level' => 28],
            ],
        ],
        'harvesting.toolWear' => [
            'job' => 'harvesting',
            'kind' => 'toolWear',
            'name' => 'Tool Care',
            'description' => 'Mines that leave the line\'s tool untouched.',
            'ranks' => [
                ['node' => 'harvesting.sharp_hook', 'level' => 1],
                ['node' => 'harvesting.hook_stoning', 'level' => 5],
                ['node' => 'harvesting.peened_edge', 'level' => 5],
                ['node' => 'harvesting.snath_fitting', 'level' => 12],
                ['node' => 'harvesting.dry_blade', 'level' => 12],
                ['node' => 'harvesting.handcart', 'level' => 12],
                ['node' => 'harvesting.blade_case', 'level' => 20],
                ['node' => 'harvesting.blade_setting', 'level' => 20],
                ['node' => 'harvesting.field_reeve', 'level' => 28],
            ],
        ],
        'woodcutting.stat' => [
            'job' => 'woodcutting',
            'kind' => 'stat',
            'name' => 'Woodsman\'s Eye',
            'description' => 'A bigger haul off a forest hex.',
            'ranks' => [
                ['node' => 'woodcutting.felling_notch', 'level' => 1],
                ['node' => 'woodcutting.deer_paths', 'level' => 1],
                ['node' => 'woodcutting.limb_reading', 'level' => 1],
                ['node' => 'woodcutting.grain_split', 'level' => 5],
                ['node' => 'woodcutting.sap_timing', 'level' => 5],
                ['node' => 'woodcutting.crosscut_pair', 'level' => 5],
                ['node' => 'woodcutting.heartwood_cut', 'level' => 12],
                ['node' => 'woodcutting.stump_yield', 'level' => 12],
                ['node' => 'woodcutting.quarter_sawing', 'level' => 20],
                ['node' => 'woodcutting.clean_stump', 'level' => 20],
            ],
        ],
        'explorer.bagSlots' => [
            'job' => 'explorer',
            'kind' => 'bagSlots',
            'name' => 'Straps',
            'description' => 'Places on the bag to put something.',
            'ranks' => [
                ['node' => 'explorer.deep_pockets', 'level' => 2],
                ['node' => 'explorer.second_strap', 'level' => 4],
                ['node' => 'explorer.rolled_blanket', 'level' => 6],
                ['node' => 'explorer.even_load', 'level' => 8],
                ['node' => 'explorer.side_pouch', 'level' => 10],
                ['node' => 'explorer.bindle', 'level' => 14],
                ['node' => 'explorer.sorted_kit', 'level' => 16],
                ['node' => 'explorer.tump_line', 'level' => 18],
                ['node' => 'explorer.packers_knot', 'level' => 20],
                ['node' => 'explorer.outer_pockets', 'level' => 22],
                ['node' => 'explorer.long_haul', 'level' => 24],
                ['node' => 'explorer.drovers_back', 'level' => 26],
                ['node' => 'explorer.tinkers_roll', 'level' => 28],
            ],
        ],
        'shieldbearer.anvil_stance' => [
            'job' => 'shieldbearer',
            'kind' => 'battleSkill',
            'name' => 'Anvil Stance',
            'description' => 'One of the three a Shieldbearer carries into a fight.',
            'ranks' => [
                ['node' => 'shieldbearer.anvil_stance', 'level' => 5],
            ],
        ],
        'shieldbearer.weaponWear' => [
            'job' => 'shieldbearer',
            'kind' => 'weaponWear',
            'name' => 'Blade Care',
            'description' => 'The same for the blade, which pays its own stream.',
            'ranks' => [
                ['node' => 'shieldbearer.helm_awareness', 'level' => 5],
                ['node' => 'shieldbearer.watchful_rest', 'level' => 12],
            ],
        ],
        'swordhand.weaponWear' => [
            'job' => 'swordhand',
            'kind' => 'weaponWear',
            'name' => 'Blade Care',
            'description' => 'The same for the blade, which pays its own stream.',
            'ranks' => [
                ['node' => 'swordhand.edge_alignment', 'level' => 5],
                ['node' => 'swordhand.sword_care', 'level' => 12],
            ],
        ],
        'runecaster.weaponWear' => [
            'job' => 'runecaster',
            'kind' => 'weaponWear',
            'name' => 'Blade Care',
            'description' => 'The same for the blade, which pays its own stream.',
            'ranks' => [
                ['node' => 'runecaster.slow_charge', 'level' => 5],
                ['node' => 'runecaster.cinder_hand', 'level' => 5],
                ['node' => 'runecaster.echo_carve', 'level' => 12],
                ['node' => 'runecaster.steady_channel', 'level' => 12],
                ['node' => 'runecaster.true_bedding', 'level' => 28],
            ],
        ],
        'runecaster.chain_arc' => [
            'job' => 'runecaster',
            'kind' => 'battleSkill',
            'name' => 'Chain Arc',
            'description' => 'One of the three a Runecaster carries into a fight.',
            'ranks' => [
                ['node' => 'runecaster.chain_arc', 'level' => 5],
            ],
        ],
        'smith.optionTier' => [
            'job' => 'smith',
            'kind' => 'optionTier',
            'name' => 'Deep Draw',
            'description' => 'Chance a rolled line is drawn a grade deeper.',
            'ranks' => [
                ['node' => 'smith.edge_geometry', 'level' => 5],
                ['node' => 'smith.anvil_song', 'level' => 5],
                ['node' => 'smith.pattern_weld', 'level' => 12],
                ['node' => 'smith.blank_stamping', 'level' => 12],
                ['node' => 'smith.heat_ledger', 'level' => 20],
                ['node' => 'smith.shop_of_record', 'level' => 28],
            ],
        ],
        'armorer.optionTier' => [
            'job' => 'armorer',
            'kind' => 'optionTier',
            'name' => 'Deep Draw',
            'description' => 'Chance a rolled line is drawn a grade deeper.',
            'ranks' => [
                ['node' => 'armorer.weight_balance', 'level' => 5],
                ['node' => 'armorer.articulation', 'level' => 12],
                ['node' => 'armorer.bespoke_fitting', 'level' => 20],
                ['node' => 'armorer.cold_weather_lining', 'level' => 20],
            ],
        ],
        'swordhand.goldFind' => [
            'job' => 'swordhand',
            'kind' => 'goldFind',
            'name' => 'Purse',
            'description' => 'More of what a pack pays.',
            'ranks' => [
                ['node' => 'swordhand.tempo_break', 'level' => 5],
                ['node' => 'swordhand.rust_watch', 'level' => 20],
                ['node' => 'swordhand.the_kept_edge', 'level' => 28],
            ],
        ],
        'alchemist.batch' => [
            'job' => 'alchemist',
            'kind' => 'batch',
            'name' => 'Rack',
            'description' => 'More flasks off a brew.',
            'ranks' => [
                ['node' => 'alchemist.batch_kettle', 'level' => 5],
                ['node' => 'alchemist.rack_brewing', 'level' => 12],
            ],
        ],
        'shieldbearer.skillPower' => [
            'job' => 'shieldbearer',
            'kind' => 'skillPower',
            'name' => 'Skill Power',
            'description' => 'More of the extra on your family\'s three skills.',
            'ranks' => [
                ['node' => 'shieldbearer.weight_forward', 'level' => 5],
            ],
        ],
        'swordhand.skillCooldown' => [
            'job' => 'swordhand',
            'kind' => 'skillCooldown',
            'name' => 'Skill Tempo',
            'description' => 'Whole rounds off every one of their cooldowns.',
            'ranks' => [
                ['node' => 'swordhand.double_time', 'level' => 5],
                ['node' => 'swordhand.duelist_calm', 'level' => 12],
            ],
        ],
        'runecaster.skillCooldown' => [
            'job' => 'runecaster',
            'kind' => 'skillCooldown',
            'name' => 'Skill Tempo',
            'description' => 'Whole rounds off every one of their cooldowns.',
            'ranks' => [
                ['node' => 'runecaster.deep_vein', 'level' => 5],
                ['node' => 'runecaster.open_channel', 'level' => 12],
            ],
        ],
        'swordhand.sunder' => [
            'job' => 'swordhand',
            'kind' => 'battleSkill',
            'name' => 'Sunder',
            'description' => 'One of the three a Swordhand carries into a fight.',
            'ranks' => [
                ['node' => 'swordhand.sunder', 'level' => 5],
            ],
        ],
        'sawyer.batch' => [
            'job' => 'sawyer',
            'kind' => 'batch',
            'name' => 'Yield Batch',
            'description' => 'More output per run.',
            'ranks' => [
                ['node' => 'sawyer.gang_blades', 'level' => 5],
                ['node' => 'sawyer.stacked_cuts', 'level' => 12],
            ],
        ],
        'smelter.batch' => [
            'job' => 'smelter',
            'kind' => 'batch',
            'name' => 'Yield Batch',
            'description' => 'More output per run.',
            'ranks' => [
                ['node' => 'smelter.double_crucible', 'level' => 5],
                ['node' => 'smelter.ingot_molds', 'level' => 12],
            ],
        ],
        'tanner.batch' => [
            'job' => 'tanner',
            'kind' => 'batch',
            'name' => 'Yield Batch',
            'description' => 'More output per run.',
            'ranks' => [
                ['node' => 'tanner.layered_pit', 'level' => 5],
                ['node' => 'tanner.paired_pits', 'level' => 12],
            ],
        ],
        'mason.batch' => [
            'job' => 'mason',
            'kind' => 'batch',
            'name' => 'Yield Batch',
            'description' => 'More output per run.',
            'ranks' => [
                ['node' => 'mason.ganged_blocks', 'level' => 5],
                ['node' => 'mason.double_banker', 'level' => 12],
            ],
        ],
        'weaver.batch' => [
            'job' => 'weaver',
            'kind' => 'batch',
            'name' => 'Yield Batch',
            'description' => 'More output per run.',
            'ranks' => [
                ['node' => 'weaver.double_shuttle', 'level' => 5],
                ['node' => 'weaver.two_beam_warp', 'level' => 12],
            ],
        ],
        'explorer.sight' => [
            'job' => 'explorer',
            'kind' => 'sight',
            'name' => 'Horizon',
            'description' => 'How many hexes of live ground you can read.',
            'ranks' => [
                ['node' => 'explorer.high_ground', 'level' => 12],
                ['node' => 'explorer.horizon_line', 'level' => 30],
            ],
        ],
        'runecaster.goldFind' => [
            'job' => 'runecaster',
            'kind' => 'goldFind',
            'name' => 'Purse',
            'description' => 'More of what a pack pays.',
            'ranks' => [
                ['node' => 'runecaster.ash_reading', 'level' => 12],
            ],
        ],
        'swordhand.riposte' => [
            'job' => 'swordhand',
            'kind' => 'battleSkill',
            'name' => 'Riposte',
            'description' => 'One of the three a Swordhand carries into a fight.',
            'ranks' => [
                ['node' => 'swordhand.riposte', 'level' => 12],
            ],
        ],
        'runecaster.rune_of_binding' => [
            'job' => 'runecaster',
            'kind' => 'battleSkill',
            'name' => 'Rune of Binding',
            'description' => 'One of the three a Runecaster carries into a fight.',
            'ranks' => [
                ['node' => 'runecaster.rune_of_binding', 'level' => 12],
            ],
        ],
        'swordhand.lootOption' => [
            'job' => 'swordhand',
            'kind' => 'lootOption',
            'name' => 'Scavenger',
            'description' => 'Chance of an extra rolled line on looted gear.',
            'ranks' => [
                ['node' => 'swordhand.the_even_hand', 'level' => 12],
            ],
        ],
        'swordhand.skillPower' => [
            'job' => 'swordhand',
            'kind' => 'skillPower',
            'name' => 'Skill Power',
            'description' => 'More of the extra on your family\'s three skills.',
            'ranks' => [
                ['node' => 'swordhand.committed_edge', 'level' => 12],
                ['node' => 'swordhand.opening_read', 'level' => 20],
            ],
        ],
        'shieldbearer.skillCooldown' => [
            'job' => 'shieldbearer',
            'kind' => 'skillCooldown',
            'name' => 'Skill Tempo',
            'description' => 'Whole rounds off every one of their cooldowns.',
            'ranks' => [
                ['node' => 'shieldbearer.second_wind', 'level' => 12],
                ['node' => 'shieldbearer.recovered_stance', 'level' => 20],
            ],
        ],
        'shieldbearer.wardens_toll' => [
            'job' => 'shieldbearer',
            'kind' => 'battleSkill',
            'name' => 'Warden\'s Toll',
            'description' => 'One of the three a Shieldbearer carries into a fight.',
            'ranks' => [
                ['node' => 'shieldbearer.wardens_toll', 'level' => 12],
            ],
        ],
        'shieldbearer.skillStun' => [
            'job' => 'shieldbearer',
            'kind' => 'skillStun',
            'name' => 'Heavy Hand',
            'description' => 'A round longer on a stun.',
            'ranks' => [
                ['node' => 'shieldbearer.ringing_blow', 'level' => 20],
            ],
        ],
        'swordhand.skillStun' => [
            'job' => 'swordhand',
            'kind' => 'skillStun',
            'name' => 'Heavy Hand',
            'description' => 'A round longer on a stun.',
            'ranks' => [
                ['node' => 'swordhand.pommel_strike', 'level' => 20],
            ],
        ],
        'runecaster.skillStun' => [
            'job' => 'runecaster',
            'kind' => 'skillStun',
            'name' => 'Heavy Hand',
            'description' => 'A round longer on a stun.',
            'ranks' => [
                ['node' => 'runecaster.stilling_word', 'level' => 20],
            ],
        ],
        'shieldbearer.goldFind' => [
            'job' => 'shieldbearer',
            'kind' => 'goldFind',
            'name' => 'Purse',
            'description' => 'More of what a pack pays.',
            'ranks' => [
                ['node' => 'shieldbearer.kit_discipline', 'level' => 28],
            ],
        ],
        'shieldbearer.lootOption' => [
            'job' => 'shieldbearer',
            'kind' => 'lootOption',
            'name' => 'Scavenger',
            'description' => 'Chance of an extra rolled line on looted gear.',
            'ranks' => [
                ['node' => 'shieldbearer.the_long_watch', 'level' => 28],
            ],
        ],
        'runecaster.lootOption' => [
            'job' => 'runecaster',
            'kind' => 'lootOption',
            'name' => 'Scavenger',
            'description' => 'Chance of an extra rolled line on looted gear.',
            'ranks' => [
                ['node' => 'runecaster.the_kept_word', 'level' => 28],
            ],
        ],
        'sawyer.runSlot' => [
            'job' => 'sawyer',
            'kind' => 'runSlot',
            'name' => 'Second Pit',
            'description' => 'Runs of this line you may keep going at once.',
            'ranks' => [
                ['node' => 'sawyer.the_long_pit', 'level' => 28],
                ['node' => 'sawyer.timber_reeve', 'level' => 28],
            ],
        ],
        'smelter.runSlot' => [
            'job' => 'smelter',
            'kind' => 'runSlot',
            'name' => 'Second Pit',
            'description' => 'Runs of this line you may keep going at once.',
            'ranks' => [
                ['node' => 'smelter.the_long_blast', 'level' => 28],
                ['node' => 'smelter.master_of_the_stack', 'level' => 28],
            ],
        ],
        'tanner.runSlot' => [
            'job' => 'tanner',
            'kind' => 'runSlot',
            'name' => 'Second Pit',
            'description' => 'Runs of this line you may keep going at once.',
            'ranks' => [
                ['node' => 'tanner.the_deep_pit', 'level' => 28],
                ['node' => 'tanner.master_tanner', 'level' => 28],
            ],
        ],
        'mason.runSlot' => [
            'job' => 'mason',
            'kind' => 'runSlot',
            'name' => 'Second Pit',
            'description' => 'Runs of this line you may keep going at once.',
            'ranks' => [
                ['node' => 'mason.the_great_banker', 'level' => 28],
                ['node' => 'mason.master_mason', 'level' => 28],
            ],
        ],
        'weaver.runSlot' => [
            'job' => 'weaver',
            'kind' => 'runSlot',
            'name' => 'Second Pit',
            'description' => 'Runs of this line you may keep going at once.',
            'ranks' => [
                ['node' => 'weaver.the_long_warp', 'level' => 28],
                ['node' => 'weaver.master_weaver', 'level' => 28],
            ],
        ],
    ];

    /** Every skill a job teaches, in the order it becomes available. */
    public static function forJob(string $job): array
    {
        return array_filter(self::ALL, static fn (array $s) => $s['job'] === $job);
    }

    public static function of(string $key): ?array
    {
        return self::ALL[$key] ?? null;
    }

    /** How many ranks this skill climbs to. */
    public static function rankCount(string $key): int
    {
        return count(self::ALL[$key]['ranks'] ?? []);
    }

    /**
     * The job level that opens a given rank, 1-indexed, or null past the top.
     *
     * This is the whole gate: a rank is reachable when the job has reached the
     * level on it, exactly as a tier used to open a row.
     */
    public static function levelForRank(string $key, int $rank): ?int
    {
        return self::ALL[$key]['ranks'][$rank - 1]['level'] ?? null;
    }

    /**
     * The Jobs::NODES keys a holding of `rank` ranks amounts to.
     *
     * This is the join that keeps the balance still: effects are still summed
     * off nodes (GameService::effectsOf), so a skill at rank 5 is exactly the
     * first five nodes it was made of and cannot be worth anything else.
     *
     * @return list<string>
     */
    public static function nodesUpTo(string $key, int $rank): array
    {
        $ranks = array_slice(self::ALL[$key]['ranks'] ?? [], 0, max(0, $rank));

        return array_column($ranks, 'node');
    }

    /**
     * Which skill a node became, for anything still speaking in nodes.
     *
     * Built once per request rather than stored: it is a pure inversion of the
     * table above, and a second copy of it in the file would be a second thing
     * to regenerate.
     */
    public static function skillForNode(string $node): ?string
    {
        static $map = null;

        if ($map === null) {
            $map = [];
            foreach (self::ALL as $key => $skill) {
                foreach ($skill['ranks'] as $i => $rank) {
                    $map[$rank['node']] = [$key, $i + 1];
                }
            }
        }

        return $map[$node][0] ?? null;
    }

    /** Which rank of its skill a node is, 1-indexed. */
    public static function rankForNode(string $node): ?int
    {
        self::skillForNode($node);

        foreach (self::ALL as $key => $skill) {
            foreach ($skill['ranks'] as $i => $rank) {
                if ($rank['node'] === $node) {
                    return $i + 1;
                }
            }
        }

        return null;
    }}
