<?php

declare(strict_types=1);

namespace App\Game;

/**
 * Generated by scripts/gen_monsters.py -- do not edit by hand.
 *
 * §9.5.8 Tier 1 -- what comes off a monster. Two families of five: a plate/hide
 * line the smith and the armorer want, an ichor/organ line the consumable bench
 * wants. Biome-free, because they come off a thing that walked there rather than
 * out of the ground, and dropped by nothing else.
 *
 * Combat feeds combat. Nothing here enters the mining economy, which is what makes
 * a whole new faucet safe under §2.
 */
final class Spoils
{
    /** §9.5.8 Tier 1 -- monster parts. Biome-free, dropped by nothing else. */
    public const STOCK = [
        'cracked_carapace' => ['name' => 'Cracked Carapace', 'tier' => 1, 'palette' => 'pelt', 'spoil' => 'plate', 'grade' => 1, 'npcPrice' => 4, 'description' => 'Comes off in sheets and takes a rivet without splitting. Most of it is waste.'],
        'bone_plate' => ['name' => 'Bone Plate', 'tier' => 1, 'palette' => 'pelt', 'spoil' => 'plate', 'grade' => 2, 'npcPrice' => 7, 'description' => 'Flat, dense, and already the right shape. The armorer barely has to cut.'],
        'scaled_hide' => ['name' => 'Scaled Hide', 'tier' => 1, 'palette' => 'pelt', 'spoil' => 'plate', 'grade' => 3, 'npcPrice' => 11, 'description' => 'Overlapped the whole way down. Turns a point that a flat hide would let through.'],
        'warped_barb' => ['name' => 'Warped Barb', 'tier' => 1, 'palette' => 'pelt', 'spoil' => 'plate', 'grade' => 4, 'npcPrice' => 17, 'description' => 'Grew wrong and hardened that way. Holds an edge nothing whetted can match.'],
        'revenant_plate' => ['name' => 'Revenant Plate', 'tier' => 1, 'palette' => 'pelt', 'spoil' => 'plate', 'grade' => 5, 'npcPrice' => 26, 'description' => 'Still warm. The smith works it fast, before it remembers what it was.'],
        'thin_ichor' => ['name' => 'Thin Ichor', 'tier' => 1, 'palette' => 'stone', 'spoil' => 'ichor', 'grade' => 1, 'npcPrice' => 3, 'description' => 'Runs like water and keeps for a week in a stoppered flask. Barely worth the flask.'],
        'black_blood' => ['name' => 'Black Blood', 'tier' => 1, 'palette' => 'stone', 'spoil' => 'ichor', 'grade' => 2, 'npcPrice' => 6, 'description' => 'Thick enough to draw a line with. The alchemist wants it for what it will not mix with.'],
        'bile_sac' => ['name' => 'Bile Sac', 'tier' => 1, 'palette' => 'stone', 'spoil' => 'ichor', 'grade' => 3, 'npcPrice' => 10, 'description' => 'Cut it out whole or lose the lot. Everything downstream of this is a nerve tonic.'],
        'ember_gland' => ['name' => 'Ember Gland', 'tier' => 1, 'palette' => 'stone', 'spoil' => 'ichor', 'grade' => 4, 'npcPrice' => 16, 'description' => 'Hot in the hand an hour after the thing stopped moving.'],
        'grave_heart' => ['name' => 'Grave Heart', 'tier' => 1, 'palette' => 'stone', 'spoil' => 'ichor', 'grade' => 5, 'npcPrice' => 25, 'description' => 'It beat once on the bench. Nobody who saw it wants to talk about it.'],
    ];

    /** Grade -> the two things a monster of that tier gives up. */
    public const BY_GRADE = [
        1 => ['plate' => 'cracked_carapace', 'ichor' => 'thin_ichor'],
        2 => ['plate' => 'bone_plate', 'ichor' => 'black_blood'],
        3 => ['plate' => 'scaled_hide', 'ichor' => 'bile_sac'],
        4 => ['plate' => 'warped_barb', 'ichor' => 'ember_gland'],
        5 => ['plate' => 'revenant_plate', 'ichor' => 'grave_heart'],
    ];
}
