<?php

declare(strict_types=1);

namespace App\Game;

/**
 * Generated by scripts/gen_toptier.py -- do not edit by hand.
 *
 * §8.0 -- the two rungs above epic. Neither is reachable and both are defined, so
 * the whole six-rung ladder can be read off one page.
 *
 * Legendary needs a guild hall, which a guild founds and builds out (§10.5).
 * Unique has no bench and no recipe at all: it drops, and it is soulbound the
 * moment it lands, because §2 forbids a grind-to-external-value faucet and a
 * tradeable drop would be exactly that.
 *
 * The `weapon` slot is absent here on purpose: battle gear runs its own full
 * ladder in `gen_battlegear.py`, three families wide at every rung, and a
 * sixteenth top-tier weapon would be a second answer to a question that file has
 * already answered.
 */
final class TopTier
{
    /** §8.0 -- legendary and unique, eight slots each bar the empty one. */
    public const ITEMS = [
        'grovefeller' => ['name' => 'Grovefeller', 'slot' => 'axe', 'rarity' => 'legendary', 'tradeable' => true, 'palette' => 'wood', 'attack' => 17, 'defense' => 0, 'station' => 'guild', 'maxDurability' => 240, 'inputs' => ['ironwood' => 5, 'heartoak' => 10, 'bentwood' => 6, 'heartknot' => 6, 'reinforced_frame' => 3, 'core' => 1], 'description' => 'Two hands and a full swing. The stand goes quiet around it.'],
        'the_last_bough' => ['name' => 'The Last Bough', 'slot' => 'axe', 'rarity' => 'unique', 'tradeable' => false, 'palette' => 'wood', 'attack' => 19, 'defense' => 0, 'maxDurability' => 260, 'perk' => 'Reads the grade of every forest hex inside sight, unworked or not.', 'description' => 'Older than the grove it came out of, and the grove was there first.'],
        'deepreach' => ['name' => 'Deepreach', 'slot' => 'pickaxe', 'rarity' => 'legendary', 'tradeable' => true, 'palette' => 'iron', 'attack' => 17, 'defense' => 0, 'station' => 'guild', 'maxDurability' => 240, 'inputs' => ['mythril_ore' => 5, 'meteoric_iron' => 10, 'skysteel' => 6, 'flux_salt' => 6, 'reinforced_frame' => 3, 'core' => 1], 'description' => 'Made for seams that start below where anyone has dug.'],
        'mothervein' => ['name' => 'Mothervein', 'slot' => 'pickaxe', 'rarity' => 'unique', 'tradeable' => false, 'palette' => 'iron', 'attack' => 19, 'defense' => 0, 'maxDurability' => 260, 'perk' => 'Names the seam a mountain hex is hiding before the first swing.', 'description' => 'It hums on the walk in, and louder the closer you get.'],
        'farshot' => ['name' => 'Farshot', 'slot' => 'bow', 'rarity' => 'legendary', 'tradeable' => true, 'palette' => 'pelt', 'attack' => 17, 'defense' => 0, 'station' => 'guild', 'maxDurability' => 240, 'inputs' => ['beastfang_hide' => 5, 'dire_pelt' => 10, 'lacquered_hide' => 6, 'horn' => 6, 'reinforced_frame' => 3, 'core' => 1], 'description' => 'Loosed from the treeline. Nothing on the range hears the first one.'],
        'the_quiet_mile' => ['name' => 'The Quiet Mile', 'slot' => 'bow', 'rarity' => 'unique', 'tradeable' => false, 'palette' => 'pelt', 'attack' => 19, 'defense' => 0, 'maxDurability' => 260, 'perk' => 'A herd will not leave the hex you are standing on.', 'description' => 'Drawn once at the treeline. Nothing on the range has ever heard it.'],
        'hillbreaker' => ['name' => 'Hillbreaker', 'slot' => 'hammer', 'rarity' => 'legendary', 'tradeable' => true, 'palette' => 'stone', 'attack' => 17, 'defense' => 0, 'station' => 'guild', 'maxDurability' => 240, 'inputs' => ['obsidian_shard' => 5, 'granite' => 10, 'polished_granite' => 6, 'whetgrit' => 6, 'reinforced_frame' => 3, 'core' => 1], 'description' => 'The face does not chip. It opens, all at once, along a line you chose.'],
        'the_standing_stone' => ['name' => 'The Standing Stone', 'slot' => 'hammer', 'rarity' => 'unique', 'tradeable' => false, 'palette' => 'stone', 'attack' => 19, 'defense' => 0, 'maxDurability' => 260, 'perk' => 'Never breaks: it drops to its last point of durability and stops there.', 'description' => 'Someone set it upright a long time ago and it has not moved since.'],
        'longreap' => ['name' => 'Longreap', 'slot' => 'sickle', 'rarity' => 'legendary', 'tradeable' => true, 'palette' => 'fiber', 'attack' => 17, 'defense' => 0, 'station' => 'guild', 'maxDurability' => 240, 'inputs' => ['silkweave_fiber' => 5, 'hemp' => 10, 'canvas' => 6, 'quench_reed' => 6, 'reinforced_frame' => 3, 'core' => 1], 'description' => 'A field in one pass, and the stubble left standing to the inch.'],
        'the_long_acre' => ['name' => 'The Long Acre', 'slot' => 'sickle', 'rarity' => 'unique', 'tradeable' => false, 'palette' => 'fiber', 'attack' => 19, 'defense' => 0, 'maxDurability' => 260, 'perk' => 'A worked grassland hex regrows on its own clock, not the map’s.', 'description' => 'The field it was named for is still cut every year by nobody.'],
        'wardencoat' => ['name' => 'Wardencoat', 'slot' => 'armor', 'rarity' => 'legendary', 'tradeable' => true, 'stat' => 'tripReduction', 'value' => 0.14, 'palette' => 'wood', 'attack' => 1, 'defense' => 9, 'station' => 'guild', 'maxDurability' => 240, 'inputs' => ['ironwood' => 5, 'heartoak' => 10, 'bentwood' => 6, 'pine_pitch' => 6, 'reinforced_frame' => 3, 'core' => 1], 'description' => 'Grown, boiled and banded. Worn by people who walk the contested ring twice a day.'],
        'coat_of_ash' => ['name' => 'Coat of Ash', 'slot' => 'armor', 'rarity' => 'unique', 'tradeable' => false, 'stat' => 'tripReduction', 'value' => 0.15, 'palette' => 'wood', 'attack' => 2, 'defense' => 10, 'maxDurability' => 260, 'perk' => 'Weather on the contested ring costs you nothing at all.', 'description' => 'Came out of the Ashpit on someone who did not.'],
        'leaguewalkers' => ['name' => 'Leaguewalkers', 'slot' => 'boots', 'rarity' => 'legendary', 'tradeable' => true, 'stat' => 'travelSpeed', 'value' => 0.14, 'palette' => 'pelt', 'attack' => 0, 'defense' => 5, 'station' => 'guild', 'maxDurability' => 240, 'inputs' => ['beastfang_hide' => 5, 'dire_pelt' => 10, 'lacquered_hide' => 6, 'sinew' => 6, 'reinforced_frame' => 3, 'core' => 1], 'description' => 'Cut for the road between rings. The miles stop being the argument.'],
        'the_wanderers_debt' => ['name' => 'The Wanderer\'s Debt', 'slot' => 'boots', 'rarity' => 'unique', 'tradeable' => false, 'stat' => 'travelSpeed', 'value' => 0.15, 'palette' => 'pelt', 'attack' => 0, 'defense' => 6, 'maxDurability' => 260, 'perk' => 'The road pays Explorer experience whether you arrive or turn back.', 'description' => 'Worn through and mended eleven times. None of the mending is yours.'],
        'steadyhands' => ['name' => 'Steadyhands', 'slot' => 'gloves', 'rarity' => 'legendary', 'tradeable' => true, 'stat' => 'processingSpeed', 'value' => 0.14, 'palette' => 'fiber', 'attack' => 5, 'defense' => 1, 'station' => 'guild', 'maxDurability' => 240, 'inputs' => ['silkweave_fiber' => 5, 'hemp' => 10, 'canvas' => 6, 'beeswax' => 6, 'reinforced_frame' => 3, 'core' => 1], 'description' => 'Every line foreman in the capital knows the pattern and none can afford it.'],
        'coldforge' => ['name' => 'Coldforge', 'slot' => 'gloves', 'rarity' => 'unique', 'tradeable' => false, 'stat' => 'processingSpeed', 'value' => 0.15, 'palette' => 'fiber', 'attack' => 6, 'defense' => 2, 'maxDurability' => 260, 'perk' => 'A processing queue you are standing in never counts you as absent.', 'description' => 'Warm to hold in any weather, which is the wrong way round.'],
    ];
}
