<?php

declare(strict_types=1);

namespace App\Game;

/**
 * Generated by scripts/gen_variants.py -- do not edit by hand.
 *
 * §5.3 -- four tile variants per biome, one per equipment rung, and the variant
 * is what decides which grade of material the hex gives up. The Tier 3 rare is
 * one of the four, so contested ground stops borrowing the base biome's sprite.
 */
final class Variants
{
    /** The four grades, in ladder order. A variant's grade is its rung. */
    public const GRADES = ['common', 'uncommon', 'rare', 'epic'];

    /**
     * Biome -> its four variants, in grade order.
     *
     * `weights` is the chance this variant is what a hex turns out to be,
     * per ring. Each ring column sums to 1 across a biome, and the walk in
     * WorldGen::variantOf() depends on that.
     */
    public const BIOME_VARIANTS = [
        'forest' => [
            ['key' => 'forest', 'grade' => 'common', 'name' => 'Forest', 'material' => 'wood', 'tint' => '#5f8058', 'props' => 'conifers', 'weights' => ['outer' => 0.975, 'mid' => 0.68, 'inner' => 0.42]],
            ['key' => 'forest_uncommon', 'grade' => 'uncommon', 'name' => 'Hardwood Stand', 'material' => 'hardwood', 'tint' => '#6b8a4e', 'props' => 'broadleaf', 'weights' => ['outer' => 0.02, 'mid' => 0.3, 'inner' => 0.25]],
            ['key' => 'forest_rare', 'grade' => 'rare', 'name' => 'Old Growth', 'material' => 'heartoak', 'tint' => '#46654a', 'props' => 'giants', 'weights' => ['outer' => 0.005, 'mid' => 0.02, 'inner' => 0.15]],
            ['key' => 'forest_epic', 'grade' => 'epic', 'name' => 'Ironwood Grove', 'material' => 'ironwood', 'tint' => '#55705f', 'props' => 'ironwood', 'weights' => ['outer' => 0.0, 'mid' => 0.0, 'inner' => 0.18]],
        ],
        'mountain' => [
            ['key' => 'mountain', 'grade' => 'common', 'name' => 'Mountain', 'material' => 'iron_ore', 'tint' => '#6d8399', 'props' => 'peaks', 'weights' => ['outer' => 0.975, 'mid' => 0.68, 'inner' => 0.42]],
            ['key' => 'mountain_uncommon', 'grade' => 'uncommon', 'name' => 'Hematite Ridge', 'material' => 'hematite', 'tint' => '#8a7a72', 'props' => 'banded', 'weights' => ['outer' => 0.02, 'mid' => 0.3, 'inner' => 0.25]],
            ['key' => 'mountain_rare', 'grade' => 'rare', 'name' => 'Crater Field', 'material' => 'meteoric_iron', 'tint' => '#5c6b7d', 'props' => 'crater', 'weights' => ['outer' => 0.005, 'mid' => 0.02, 'inner' => 0.15]],
            ['key' => 'mountain_epic', 'grade' => 'epic', 'name' => 'Mythril Seam', 'material' => 'mythril_ore', 'tint' => '#7d93a8', 'props' => 'mythril', 'weights' => ['outer' => 0.0, 'mid' => 0.0, 'inner' => 0.18]],
        ],
        'plains' => [
            ['key' => 'plains', 'grade' => 'common', 'name' => 'Plains', 'material' => 'pelt', 'tint' => '#b08a5a', 'props' => 'tufts', 'weights' => ['outer' => 0.975, 'mid' => 0.68, 'inner' => 0.42]],
            ['key' => 'plains_uncommon', 'grade' => 'uncommon', 'name' => 'Herd Range', 'material' => 'thick_pelt', 'tint' => '#bb9a63', 'props' => 'grazed', 'weights' => ['outer' => 0.02, 'mid' => 0.3, 'inner' => 0.25]],
            ['key' => 'plains_rare', 'grade' => 'rare', 'name' => 'Dire Range', 'material' => 'dire_pelt', 'tint' => '#96703f', 'props' => 'bones', 'weights' => ['outer' => 0.005, 'mid' => 0.02, 'inner' => 0.15]],
            ['key' => 'plains_epic', 'grade' => 'epic', 'name' => 'Beastfang Reach', 'material' => 'beastfang_hide', 'tint' => '#a37452', 'props' => 'fangs', 'weights' => ['outer' => 0.0, 'mid' => 0.0, 'inner' => 0.18]],
        ],
        'badlands' => [
            ['key' => 'badlands', 'grade' => 'common', 'name' => 'Badlands', 'material' => 'stone', 'tint' => '#96604c', 'props' => 'shards', 'weights' => ['outer' => 0.975, 'mid' => 0.68, 'inner' => 0.42]],
            ['key' => 'badlands_uncommon', 'grade' => 'uncommon', 'name' => 'Basalt Flats', 'material' => 'basalt', 'tint' => '#7a5347', 'props' => 'columns', 'weights' => ['outer' => 0.02, 'mid' => 0.3, 'inner' => 0.25]],
            ['key' => 'badlands_rare', 'grade' => 'rare', 'name' => 'Granite Shelf', 'material' => 'granite', 'tint' => '#a1756a', 'props' => 'shelf', 'weights' => ['outer' => 0.005, 'mid' => 0.02, 'inner' => 0.15]],
            ['key' => 'badlands_epic', 'grade' => 'epic', 'name' => 'Obsidian Flow', 'material' => 'obsidian_shard', 'tint' => '#5f4a52', 'props' => 'glass', 'weights' => ['outer' => 0.0, 'mid' => 0.0, 'inner' => 0.18]],
        ],
        'grassland' => [
            ['key' => 'grassland', 'grade' => 'common', 'name' => 'Grassland', 'material' => 'fiber', 'tint' => '#a8a05c', 'props' => 'tufts', 'weights' => ['outer' => 0.975, 'mid' => 0.68, 'inner' => 0.42]],
            ['key' => 'grassland_uncommon', 'grade' => 'uncommon', 'name' => 'Flax Meadow', 'material' => 'flax', 'tint' => '#b6b073', 'props' => 'flowering', 'weights' => ['outer' => 0.02, 'mid' => 0.3, 'inner' => 0.25]],
            ['key' => 'grassland_rare', 'grade' => 'rare', 'name' => 'Hemp Field', 'material' => 'hemp', 'tint' => '#8f9552', 'props' => 'tall', 'weights' => ['outer' => 0.005, 'mid' => 0.02, 'inner' => 0.15]],
            ['key' => 'grassland_epic', 'grade' => 'epic', 'name' => 'Silkweave Fen', 'material' => 'silkweave_fiber', 'tint' => '#9fa878', 'props' => 'silk', 'weights' => ['outer' => 0.0, 'mid' => 0.0, 'inner' => 0.18]],
        ],
    ];

    /** §4 Tier 1 -- the grades above the base raw, biome-locked like it. */
    public const RAW = [
        'hardwood' => ['name' => 'Hardwood', 'tier' => 1, 'biome' => 'forest', 'palette' => 'wood', 'npcPrice' => 4, 'description' => 'Broadleaf, felled standing. Twice the weight of green pine and worth carrying.'],
        'heartoak' => ['name' => 'Heartoak', 'tier' => 1, 'biome' => 'forest', 'palette' => 'wood', 'npcPrice' => 7, 'description' => 'The dark core of something that outlived everyone who saw it planted.'],
        'hematite' => ['name' => 'Hematite', 'tier' => 1, 'biome' => 'mountain', 'palette' => 'iron', 'npcPrice' => 5, 'description' => 'Ore rich enough that the slag heap is barely worth picking over.'],
        'meteoric_iron' => ['name' => 'Meteoric Iron', 'tier' => 1, 'biome' => 'mountain', 'palette' => 'iron', 'npcPrice' => 9, 'description' => 'Came down in the crater field. Takes an edge nothing smelted can hold.'],
        'thick_pelt' => ['name' => 'Thick Pelt', 'tier' => 1, 'biome' => 'plains', 'palette' => 'pelt', 'npcPrice' => 5, 'description' => 'Winter coat off a full-grown animal. Heavy, and it keeps its shape.'],
        'dire_pelt' => ['name' => 'Dire Pelt', 'tier' => 1, 'biome' => 'plains', 'palette' => 'pelt', 'npcPrice' => 9, 'description' => 'Off something that had no natural enemies until you turned up.'],
        'basalt' => ['name' => 'Basalt', 'tier' => 1, 'biome' => 'badlands', 'palette' => 'stone', 'npcPrice' => 4, 'description' => 'Cooled in columns, and it splits along them. Harder than the shale next door.'],
        'granite' => ['name' => 'Granite', 'tier' => 1, 'biome' => 'badlands', 'palette' => 'stone', 'npcPrice' => 8, 'description' => 'Speckled and stubborn. It blunts what you dress it with.'],
        'flax' => ['name' => 'Flax', 'tier' => 1, 'biome' => 'grassland', 'palette' => 'fiber', 'npcPrice' => 4, 'description' => 'Retted in the ditch for a fortnight. Spins finer than field grass ever will.'],
        'hemp' => ['name' => 'Hemp', 'tier' => 1, 'biome' => 'grassland', 'palette' => 'fiber', 'npcPrice' => 7, 'description' => 'Stems taller than a man. Nothing ordinary breaks a rope of it.'],
    ];

    /** §4 Tier 2 -- what each grade refines into. Not biome-locked. */
    public const REFINED = [
        'beams' => ['name' => 'Beams', 'tier' => 2, 'palette' => 'wood', 'npcPrice' => 14, 'description' => 'Squared off the log rather than sawn thin. Takes a load without complaining.'],
        'bentwood' => ['name' => 'Bentwood', 'tier' => 2, 'palette' => 'wood', 'npcPrice' => 26, 'description' => 'Steamed, bent round a form, and left to set. It holds the curve forever.'],
        'steel_ingots' => ['name' => 'Steel Ingots', 'tier' => 2, 'palette' => 'iron', 'npcPrice' => 18, 'description' => 'Carbon worked through the iron. Springs back where plain bar stays bent.'],
        'skysteel' => ['name' => 'Skysteel', 'tier' => 2, 'palette' => 'iron', 'npcPrice' => 32, 'description' => 'Folded out of what fell. Pale, and it rings a long time after the strike.'],
        'boiled_leather' => ['name' => 'Boiled Leather', 'tier' => 2, 'palette' => 'pelt', 'npcPrice' => 16, 'description' => 'Boiled hard and molded wet. Sets like a shell and weighs nothing.'],
        'lacquered_hide' => ['name' => 'Lacquered Hide', 'tier' => 2, 'palette' => 'pelt', 'npcPrice' => 30, 'description' => 'Layered, lacquered, and left in the dark to cure. Turns a blade.'],
        'dressed_basalt' => ['name' => 'Dressed Basalt', 'tier' => 2, 'palette' => 'stone', 'npcPrice' => 15, 'description' => 'Squared out of the column. Every face is already flat; you only true it.'],
        'polished_granite' => ['name' => 'Polished Granite', 'tier' => 2, 'palette' => 'stone', 'npcPrice' => 28, 'description' => 'Ground down through four grits. The finish is what makes it last.'],
        'linen' => ['name' => 'Linen', 'tier' => 2, 'palette' => 'fiber', 'npcPrice' => 13, 'description' => 'Woven off the flax line. Cool, strong, and it takes a dye.'],
        'canvas' => ['name' => 'Canvas', 'tier' => 2, 'palette' => 'fiber', 'npcPrice' => 25, 'description' => 'Hemp beaten flat and woven close. Rain runs off it and rope does not cut it.'],
    ];

    /** §6 -- one processing recipe per grade, same 3:1 as the base line. */
    public const PROCESSING = [
        'beams' => ['name' => 'Saw Beams', 'input' => 'hardwood', 'inputQty' => 3, 'output' => 'beams', 'outputQty' => 1, 'baseSeconds' => 16 * 60, 'skill' => 'woodcutting'],
        'bentwood' => ['name' => 'Saw Bentwood', 'input' => 'heartoak', 'inputQty' => 3, 'output' => 'bentwood', 'outputQty' => 1, 'baseSeconds' => 22 * 60, 'skill' => 'woodcutting'],
        'steel_ingots' => ['name' => 'Smelt Steel Ingots', 'input' => 'hematite', 'inputQty' => 3, 'output' => 'steel_ingots', 'outputQty' => 1, 'baseSeconds' => 19 * 60, 'skill' => 'mining'],
        'skysteel' => ['name' => 'Smelt Skysteel', 'input' => 'meteoric_iron', 'inputQty' => 3, 'output' => 'skysteel', 'outputQty' => 1, 'baseSeconds' => 26 * 60, 'skill' => 'mining'],
        'boiled_leather' => ['name' => 'Tan Boiled Leather', 'input' => 'thick_pelt', 'inputQty' => 3, 'output' => 'boiled_leather', 'outputQty' => 1, 'baseSeconds' => 17 * 60, 'skill' => 'hunting'],
        'lacquered_hide' => ['name' => 'Tan Lacquered Hide', 'input' => 'dire_pelt', 'inputQty' => 3, 'output' => 'lacquered_hide', 'outputQty' => 1, 'baseSeconds' => 24 * 60, 'skill' => 'hunting'],
        'dressed_basalt' => ['name' => 'Dress Dressed Basalt', 'input' => 'basalt', 'inputQty' => 3, 'output' => 'dressed_basalt', 'outputQty' => 1, 'baseSeconds' => 16 * 60, 'skill' => 'quarrying'],
        'polished_granite' => ['name' => 'Dress Polished Granite', 'input' => 'granite', 'inputQty' => 3, 'output' => 'polished_granite', 'outputQty' => 1, 'baseSeconds' => 23 * 60, 'skill' => 'quarrying'],
        'linen' => ['name' => 'Weave Linen', 'input' => 'flax', 'inputQty' => 3, 'output' => 'linen', 'outputQty' => 1, 'baseSeconds' => 15 * 60, 'skill' => 'harvesting'],
        'canvas' => ['name' => 'Weave Canvas', 'input' => 'hemp', 'inputQty' => 3, 'output' => 'canvas', 'outputQty' => 1, 'baseSeconds' => 21 * 60, 'skill' => 'harvesting'],
    ];

    /**
     * Which gathering line a grade belongs to, §7.2.
     *
     * Catalog::skillForMaterial() falls back to woodcutting for anything it
     * does not know, which would credit a hematite haul to the wrong tree.
     */
    public const SKILL_FOR_MATERIAL = [
        'hardwood' => 'woodcutting',
        'heartoak' => 'woodcutting',
        'hematite' => 'mining',
        'meteoric_iron' => 'mining',
        'thick_pelt' => 'hunting',
        'dire_pelt' => 'hunting',
        'basalt' => 'quarrying',
        'granite' => 'quarrying',
        'flax' => 'harvesting',
        'hemp' => 'harvesting',
    ];
}
