"""Emit the §5.5 hunting roster from one spec.

    python3 scripts/gen_hunts.py

Writes app/Game/Hunts.php and resources/js/game/hunts.ts.

An animal stands on forest and grassland ground, always, and moves on the pack
bucket. Hunting it is what mining a plains hex used to be: the hunting line's
whole ladder, carried by the creature instead of by the country.
"""
import io

# The grade ladder, lifted off the plains variants it replaces.
#
# A hex used to carry this -- Plains, Herd Range, Dire Range, Beastfang Reach --
# and the animal carries it now. The weights are the variant table's, unchanged,
# which is what keeps Beastfang Hide contested-only (§2: a Tier 3 on the safe
# rim would be the grind->NFT path the threat model exists to close).
#
# grade, material, weights by ring
GRADES = [
    ('common',   'pelt',           {'outer': 0.975, 'mid': 0.68, 'inner': 0.42}),
    ('uncommon', 'thick_pelt',     {'outer': 0.02,  'mid': 0.3,  'inner': 0.25}),
    ('rare',     'dire_pelt',      {'outer': 0.005, 'mid': 0.02, 'inner': 0.15}),
    ('contested', 'beastfang_hide', {'outer': 0.0,  'mid': 0.0,  'inner': 0.18}),
]

# key, name, biome, grade, description
#
# Two countries of four, one per grade, because the grade is what decides the
# haul and a country that shared its animals with the other would make the two
# the same walk.
ANIMALS = [
    ('roe_deer', 'Roe Deer', 'forest', 'common',
     'Feeding at the edge of the trees, and gone into them the moment you are seen.'),
    ('wood_boar', 'Wood Boar', 'forest', 'uncommon',
     'Rooting under the mast. It has no reason to run and knows it.'),
    ('bracken_elk', 'Bracken Elk', 'forest', 'rare',
     'Shoulder-high in the fern with a rack it has to turn sideways to walk.'),
    ('ironhide_stag', 'Ironhide Stag', 'forest', 'contested',
     'Nothing in the wood has taken one down in living memory. You may try.'),

    ('field_doe', 'Field Doe', 'grassland', 'common',
     'Standing in the seed heads with its ears up, which is how you find it.'),
    ('horned_ram', 'Horned Ram', 'grassland', 'uncommon',
     'Comes down the slope at you rather than away, every time.'),
    ('sedge_auroch', 'Sedge Auroch', 'grassland', 'rare',
     'Older than the settlement it grazes past, and heavier than the gate.'),
    ('beastfang_sire', 'Beastfang Sire', 'grassland', 'contested',
     'The hide is named for it. So is most of what it has eaten.'),
]

BIOMES = ['forest', 'grassland']

HEADER = """Generated by scripts/gen_hunts.py -- do not edit by hand.

§5.5 -- the hunt. What mining a plains hex used to be.

An animal stands on every workable forest and grassland hex, and it is **always
there**: a pack is a chance and this is not, because this is not a hazard, it is
the hunting line's ground. It moves on the pack's own two-hour bucket, and
killing it clears it exactly as fighting a pack clears that.

**It does not pin.** A pack owns the hex it stands on (§9.5.3), which is a
hazard a player walks around; an animal on every hex of two countries doing the
same would make those countries impassable. It is a hook on a hex that otherwise
works normally -- the same standing §9.5.7 gives a corpse.

**The GRADE is the ladder, and it is the plains variant table moved onto the
creature.** A hex used to carry Plains / Herd Range / Dire Range / Beastfang
Reach; the animal carries it now, on the same weights -- which is what keeps
Beastfang Hide contested-only without a rule of its own (§2: a Tier 3 on the
safe rim is the grind->NFT path the threat model exists to close).

**Two countries of four**, one animal per grade. A roster shared between them
would make forest and grassland the same walk, and §9.5.2 has just finished
making that argument about monsters."""


def php_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def doc(o, header, prefix=' * '):
    o.write('/**\n')
    for line in header.split('\n'):
        o.write((f'{prefix}{line}'.rstrip() + '\n') if line else ' *\n')
    o.write(' */\n')


def emit_php():
    o = io.StringIO()
    o.write('<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Game;\n\n')
    doc(o, HEADER)
    o.write('final class Hunts\n{\n')
    o.write('    /** §5.5 -- the countries an animal stands on, and no others. */\n')
    o.write("    public const BIOMES = ['" + "', '".join(BIOMES) + "'];\n\n")
    o.write('    /** §5.3 -- the grade ladder, and what each rung gives up. */\n')
    o.write('    public const GRADES = [\n')
    for grade, material, weights in GRADES:
        w = ', '.join(f"'{r}' => {v}" for r, v in weights.items())
        o.write(f"        '{grade}' => ['material' => '{material}', 'weights' => [{w}]],\n")
    o.write('    ];\n\n')
    o.write('    /** §5.5 -- the roster. Keyed by animal, one per (biome, grade). */\n')
    o.write('    public const ROSTER = [\n')
    for key, name, biome, grade, desc in ANIMALS:
        material = next(m for g, m, _ in GRADES if g == grade)
        o.write(
            f"        '{key}' => ['name' => {php_str(name)}, 'biome' => '{biome}', "
            f"'grade' => '{grade}', 'material' => '{material}', "
            f"'description' => {php_str(desc)}],\n"
        )
    o.write('    ];\n\n')
    o.write('    /** Biome -> grade -> which animal that is. */\n')
    o.write('    public const BY_BIOME_GRADE = [\n')
    for biome in BIOMES:
        o.write(f"        '{biome}' => [\n")
        for grade, _, _ in GRADES:
            key = next(a[0] for a in ANIMALS if a[2] == biome and a[3] == grade)
            o.write(f"            '{grade}' => '{key}',\n")
        o.write('        ],\n')
    o.write('    ];\n}\n')
    return o.getvalue()


def emit_ts():
    o = io.StringIO()
    doc(o, HEADER)
    o.write("import type { Animal } from './types'\n\n")
    o.write('export const HUNT_BIOMES = [' + ', '.join(f"'{b}'" for b in BIOMES) + '] as const\n\n')
    o.write('export const HUNT_GRADES: Array<{ grade: string; material: string; weights: Record<string, number> }> = [\n')
    for grade, material, weights in GRADES:
        w = ', '.join(f"{r}: {v}" for r, v in weights.items())
        o.write(f"  {{ grade: '{grade}', material: '{material}', weights: {{ {w} }} }},\n")
    o.write(']\n\n')
    o.write('export const ANIMALS: Record<string, Animal> = {\n')
    for key, name, biome, grade, desc in ANIMALS:
        material = next(m for g, m, _ in GRADES if g == grade)
        o.write(
            f"  {key}: {{ key: '{key}', name: {php_str(name)}, biome: '{biome}', "
            f"grade: '{grade}', material: '{material}', description: {php_str(desc)} }},\n"
        )
    o.write('}\n\n')
    o.write('export const ANIMAL_BY_BIOME_GRADE: Record<string, Record<string, string>> = {\n')
    for biome in BIOMES:
        o.write(f"  {biome}: {{\n")
        for grade, _, _ in GRADES:
            key = next(a[0] for a in ANIMALS if a[2] == biome and a[3] == grade)
            o.write(f"    {grade}: '{key}',\n")
        o.write('  },\n')
    o.write('}\n')
    return o.getvalue()


if __name__ == '__main__':
    keys = [a[0] for a in ANIMALS]
    assert len(keys) == len(set(keys)), 'duplicate animal key'
    assert len(ANIMALS) == len(BIOMES) * len(GRADES), 'every country needs one per grade'

    for biome in BIOMES:
        mine = [a for a in ANIMALS if a[2] == biome]
        assert {a[3] for a in mine} == {g[0] for g in GRADES}, f'{biome} is missing a grade'

    # §5.3 -- the weights are a distribution over the grades, per ring, and the
    # generator is where that is checked rather than at runtime.
    for ring in ('outer', 'mid', 'inner'):
        total = sum(w[ring] for _, _, w in GRADES)
        assert abs(total - 1.0) < 1e-9, f'{ring} weights sum to {total}'

    # §2 -- and the contested rung is reachable from the contested ring alone.
    contested = next(w for g, _, w in GRADES if g == 'contested')
    assert contested['outer'] == 0.0 and contested['mid'] == 0.0, \
        'a Tier 3 leaked onto the safe rings'

    open('app/Game/Hunts.php', 'w').write(emit_php())
    open('resources/js/game/hunts.ts', 'w').write(emit_ts())
    print(f'{len(ANIMALS)} animals across {len(BIOMES)} biomes, {len(GRADES)} grades')
