"""Emit app/Game/Critters.php and resources/js/game/critters.ts from one spec.

§4 -- the alchemist's second stock: five small animals, one per biome, and the
only ingredient that comes off a hunt rather than out of the ground.

    python3 scripts/gen_critters.py

The herbs answer "what grows here"; these answer "what lives here", which is why
they are a second stock and not ten more herbs. A recipe that wants one is a
recipe that cannot be filled by walking about with a sickle -- you need a bow
and a herd, and §5.5 puts herds on a four-hour clock. That is the whole point of
splitting the shelf: it is the difference between an errand and a hunt.
"""
import io

PALETTE = {
    'forest': 'wood', 'mountain': 'iron', 'plains': 'pelt',
    'badlands': 'stone', 'grassland': 'fiber',
}

# key, name, biome, npcPrice, description
CRITTERS = [
    ('glimmermoth', 'Glimmermoth', 'forest',    5, 'Comes to a lamp in numbers and leaves dust on everything. The dust is the part that works.'),
    ('rockmite',    'Rockmite',    'mountain',  5, 'Chews galleries through solid seam and is never seen doing it.'),
    ('dustleveret', 'Dustleveret', 'plains',    4, 'A hare the colour of the ground, and no slower for it.'),
    ('ashnewt',     'Ashnewt',     'badlands',  6, 'Sits out a vent that would cook anything else. Cold to hold, every time.'),
    ('fenlark',     'Fenlark',     'grassland', 4, 'Sings from inside the crop and never once from the top of it.'),
]

HEADER = """Generated by scripts/gen_critters.py -- do not edit by hand.

§4 Tier 1 -- the alchemist's second stock. Five small animals, one per biome,
and the only ingredient a hunt brings back rather than a gather. The herbs say
what grows on a kind of ground; these say what lives on it."""


def php_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


ts_str = php_str


def emit_php():
    o = io.StringIO()
    o.write('<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Game;\n\n')
    o.write('/**\n')
    for line in HEADER.split('\n'):
        o.write(f' * {line}\n'.rstrip() + '\n' if line else ' *\n')
    o.write(' */\nfinal class Critters\n{\n')
    o.write('    /** §4 Tier 1 -- biome-locked, hunted, and wanted by the consumable bench. */\n')
    o.write('    public const STOCK = [\n')
    for key, name, biome, price, desc in CRITTERS:
        o.write(f"        '{key}' => ['name' => {php_str(name)}, 'tier' => 1, 'biome' => '{biome}', "
                f"'palette' => '{PALETTE[biome]}', 'critter' => true, 'npcPrice' => {price}, "
                f"'description' => {php_str(desc)}],\n")
    o.write('    ];\n\n')
    o.write('    /** Biome -> the animal that lives on it. */\n')
    o.write('    public const BY_BIOME = [\n')
    for key, _, biome, _, _ in CRITTERS:
        o.write(f"        '{biome}' => '{key}',\n")
    o.write('    ];\n}\n')

    return o.getvalue()


def emit_ts():
    o = io.StringIO()
    o.write('/**\n')
    for line in HEADER.split('\n'):
        o.write(f' * {line}\n'.rstrip() + '\n' if line else ' *\n')
    o.write(" */\nimport type { Biome, Material } from './types'\n\n")
    o.write('export const CRITTERS: Material[] = [\n')
    for key, name, biome, price, desc in CRITTERS:
        o.write(f"  {{ key: '{key}', name: {ts_str(name)}, tier: 1, biome: '{biome}', "
                f"palette: '{PALETTE[biome]}', critter: true, npcPrice: {price}, "
                f"description: {ts_str(desc)} }},\n")
    o.write(']\n\n')
    o.write('export const CRITTER_BY_BIOME: Record<Biome, string> = {\n')
    for key, _, biome, _, _ in CRITTERS:
        o.write(f"  {biome}: '{key}',\n")
    o.write('}\n')

    return o.getvalue()


if __name__ == '__main__':
    keys = [c[0] for c in CRITTERS]
    assert len(keys) == len(set(keys)), 'duplicate critter key'
    assert len({c[2] for c in CRITTERS}) == 5, 'critters do not cover the five biomes'
    for key, _, _, price, _ in CRITTERS:
        assert price > 1, f'{key} sells for scrap money'

    open('app/Game/Critters.php', 'w').write(emit_php())
    open('resources/js/game/critters.ts', 'w').write(emit_ts())
    print(f'{len(CRITTERS)} critters')
