"""Emit app/Game/Components.php and resources/js/game/components.ts.

Ten craft components, hand-mirrored across PHP and TypeScript, is the same
drift gen_alchemy.py exists to prevent -- so neither side is written by hand.

    python3 scripts/gen_components.py

Read the diff afterwards. Every changed line is a price or a biome lock that
somebody's recipe already depends on.
"""
import io

PALETTE = {
    'forest': 'wood', 'mountain': 'iron',
    'badlands': 'stone', 'grassland': 'fiber',
    # §5.5 -- the hunting line is not a country, and its palette is the hide.
    'hunt': 'pelt',
}

# §4 Tier 1 -- the smith's and the armorer's raw stock, two per biome, exactly
# as the ten reagents are the alchemist's. Biome-locked, gathered off a hex,
# and every one of them sells for more than the 1-gold scrap floor, which §4.0
# makes a rule rather than a tuning value.
#
# `bench` is flavour, not a lock: it records which of the two craft benches the
# component was named for. Nothing in the code reads it -- the recipes decide.
COMPONENTS = [
    ('heartknot',   'Heartknot',   'forest',    'weapon', 4, 'The knot where a limb met the trunk. Blunts a saw and takes a haft.'),
    ('pine_pitch',  'Pine Pitch',  'forest',    'armor',  3, 'Boiled down off the bark. Everything it touches stays touched.'),
    ('flux_salt',   'Flux Salt',   'mountain',  'weapon', 4, 'Thrown on the weld so the join takes. Without it, iron only meets iron.'),
    ('slate_scale', 'Slate Scale', 'mountain',  'armor',  3, 'Splits off the seam in plates a thumb across. Overlaps like it was asked to.'),
    ('horn',        'Horn',        'hunt',      'weapon', 4, 'Cut off the herd bull and boiled soft. It remembers the shape you leave it.'),
    ('sinew',       'Sinew',       'hunt',      'armor',  3, 'Dried to a cord and split with the teeth. Stronger than anything spun.'),
    ('whetgrit',    'Whetgrit',    'badlands',  'weapon', 3, 'Sharp sand off the scree. It is what puts an edge on everything else.'),
    ('tar_seep',    'Tar Seep',    'badlands',  'armor',  3, 'Skimmed cold off a standing pool. Keeps the wet out of a boot for a season.'),
    ('quench_reed', 'Quench Reed', 'grassland', 'weapon', 2, 'Green stems packed round a hot blade. It cools slow, and slow is what holds.'),
    ('beeswax',     'Beeswax',     'grassland', 'armor',  2, 'Rendered off the comb. Waterproofs a seam and quiets a hinge.'),
]

HEADER = """Generated by scripts/gen_components.py -- do not edit by hand.

Ten craft components (§4), emitted into PHP and TypeScript from one spec so
the two catalogs cannot drift."""

DOC = """§4 Tier 1 -- craft components, biome-locked, the smith's and the
     * armorer's raw stock. Two per biome, so one recipe can want two different
     * things off a single kind of ground."""


def origin_php(biome):
    """§5.5 -- ground gets a biome; the hunting line gets a source.

    A material comes off a country or off a creature, and writing 'hunt' into
    a biome field would be a fifth biome that does not exist -- every reader
    that filters by biome would then have to know which one is a lie.
    """
    return "'source' => 'hunt', " if biome == 'hunt' else f"'biome' => '{biome}', "


def origin_ts(biome):
    return "source: 'hunt', " if biome == 'hunt' else f"biome: '{biome}', "

def emit_php():
    o = io.StringIO()
    o.write('<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Game;\n\n')
    o.write('/**\n')
    for line in HEADER.split('\n'):
        o.write(f' * {line}\n'.rstrip() + '\n' if line else ' *\n')
    o.write(' */\nfinal class Components\n{\n')
    o.write(f'    /**\n     * {DOC}\n     */\n')
    o.write('    public const CRAFT = [\n')
    for key, name, biome, bench, price, desc in COMPONENTS:
        o.write(f"        '{key}' => ['name' => '{name}', 'tier' => 1, " + origin_php(biome) + ""
                f"'palette' => '{PALETTE[biome]}', 'bench' => '{bench}', 'npcPrice' => {price}, "
                f"'description' => '{desc}'],\n")
    o.write('    ];\n}\n')

    return o.getvalue()


def emit_ts():
    o = io.StringIO()
    o.write('/**\n')
    for line in HEADER.split('\n'):
        o.write(f' * {line}\n'.rstrip() + '\n' if line else ' *\n')
    o.write(" */\nimport type { Material } from './types'\n\n")
    o.write('export const COMPONENTS: Material[] = [\n')
    for key, name, biome, bench, price, desc in COMPONENTS:
        o.write(f"  {{ key: '{key}', name: '{name}', tier: 1, " + origin_ts(biome) + ""
                f"palette: '{PALETTE[biome]}', bench: '{bench}', npcPrice: {price}, "
                f"description: '{desc}' }},\n")
    o.write(']\n')

    return o.getvalue()


if __name__ == '__main__':
    keys = [c[0] for c in COMPONENTS]
    assert len(keys) == len(set(keys)), 'duplicate component key'

    by_biome = {}
    for key, _, biome, bench, price, _ in COMPONENTS:
        by_biome.setdefault(biome, []).append(bench)
        assert price > 1, f'{key} sells for scrap money'
    assert len(by_biome) == 5, 'components do not cover the five biomes'
    for biome, benches in by_biome.items():
        assert sorted(benches) == ['armor', 'weapon'], f'{biome} is missing a bench'

    open('app/Game/Components.php', 'w').write(emit_php())
    open('resources/js/game/components.ts', 'w').write(emit_ts())
    print(f'{len(COMPONENTS)} craft components')
