"""Emit the §9.5 roster and its drops from one spec.

    python3 scripts/gen_monsters.py

Writes app/Game/Monsters.php, resources/js/game/monsters.ts, app/Game/Spoils.php
and resources/js/game/spoils.ts.

Eight monsters in four overlapping pools, two new per ring and two carried in
from the ring outside it. The overlap is the design: walking inward you meet two
you know how to fight and two you do not.

Ten spoils in two families, five grades each. A monster of tier N drops its
tier's grade, and rarely the one above -- which is what makes the guild rung's
input come off the centre ring and nowhere else.
"""
import io

# ---------------------------------------------------------------- the roster

# Player totals the numbers are aimed at, kit and battle job matched to the ring:
#
#   common kit,     job 2    atk ~10  def ~8
#   rare kit,       job 14   atk ~23  def ~21
#   epic kit,       job 20   atk ~30  def ~28
#   legendary kit,  job 28   atk ~37  def ~35
#
# A monster's attack plus its defence is what decides the fight (§9.5.5 averages
# strike and hold), so the pair is set from that sum and the profile only
# decides which half carries it.

# key, name, tier, profile, attack, defence, wearBias, gold, description
MONSTERS = [
    ('moss_hound', 'Moss Hound', 1, 'brute', 12, 5, 1.0, (4, 9),
     'Runs the treeline in threes and takes the slowest thing on the road.'),
    ('ditch_crawler', 'Ditch Crawler', 1, 'carapace', 6, 11, 1.0, (5, 11),
     'Sits in the wheel rut with its back plated over and waits to be stepped on.'),

    ('slag_ogre', 'Slag Ogre', 2, 'brute', 27, 12, 1.0, (14, 26),
     'Came down off a spoil heap and has been swinging the same girder since.'),
    ('thornback', 'Thornback', 2, 'carapace', 13, 26, 1.0, (16, 30),
     'Every quill points out. Hitting it costs you more than missing does.'),

    ('ridge_wyrm', 'Ridge Wyrm', 3, 'swift', 30, 23, 1.5, (30, 52),
     'Fast over broken ground and faster over you. It blunts whatever it is hit with.'),
    ('iron_shrike', 'Iron Shrike', 3, 'brute', 36, 17, 1.0, (33, 58),
     'Drops out of the sun onto the one thing in the party carrying metal.'),

    # The centre is the one ring that asks for battle gear rather than work gear
    # (§9.5.4). These two are sized against a full battle set, which is what
    # makes the last step inward a kit decision rather than a level one.
    ('barrow_knight', 'Barrow Knight', 4, 'carapace', 32, 58, 1.0, (60, 105),
     'Whatever it was buried in, it is still wearing. Nothing gets through the front.'),
    ('ash_revenant', 'Ash Revenant', 4, 'brute', 60, 30, 1.0, (66, 115),
     'Walked out of the centre with the fire still on it and has not stopped since.'),
]

# Which ring each tier is NEW on. A pool is its own tier plus the one outside it.
RING_OF_TIER = {1: 'outer', 2: 'mid', 3: 'inner', 4: 'center'}

# 'center' rather than 'centre': it is the Ring key the generator and the
# server already share (Balance::RING_CENTER), and prose is not a key.
RINGS = ['outer', 'mid', 'inner', 'center']

# --------------------------------------------------------------- the spoils

# Two families, five grades. Tier 1..4 monsters drop grade 1..4; the fifth grade
# is the centre ring's rare drop, which is why guild-rung gear is reachable from
# nowhere else.

# key, name, grade, npcPrice, description
PLATE = [
    ('cracked_carapace', 'Cracked Carapace', 1, 4,
     'Comes off in sheets and takes a rivet without splitting. Most of it is waste.'),
    ('bone_plate', 'Bone Plate', 2, 7,
     'Flat, dense, and already the right shape. The armorer barely has to cut.'),
    ('scaled_hide', 'Scaled Hide', 3, 11,
     'Overlapped the whole way down. Turns a point that a flat hide would let through.'),
    ('warped_barb', 'Warped Barb', 4, 17,
     'Grew wrong and hardened that way. Holds an edge nothing whetted can match.'),
    ('revenant_plate', 'Revenant Plate', 5, 26,
     'Still warm. The smith works it fast, before it remembers what it was.'),
]

ICHOR = [
    ('thin_ichor', 'Thin Ichor', 1, 3,
     'Runs like water and keeps for a week in a stoppered flask. Barely worth the flask.'),
    ('black_blood', 'Black Blood', 2, 6,
     'Thick enough to draw a line with. The alchemist wants it for what it will not mix with.'),
    ('bile_sac', 'Bile Sac', 3, 10,
     'Cut it out whole or lose the lot. Everything downstream of this is a nerve tonic.'),
    ('ember_gland', 'Ember Gland', 4, 16,
     'Hot in the hand an hour after the thing stopped moving.'),
    ('grave_heart', 'Grave Heart', 5, 25,
     'It beat once on the bench. Nobody who saw it wants to talk about it.'),
]

HEADER_MONSTERS = """Generated by scripts/gen_monsters.py -- do not edit by hand.

§9.5 -- eight monsters in four overlapping pools. Each ring adds two of its own
and carries two in from the ring outside it, so every ring is legible and
dangerous at the same time.

`attack` and `defence` are FLAT, and they are not the percentage stats of the
same name: §8.1's ceiling is +15%, and a fight cannot be decided by a swing that
small. The profile is what a player reads -- a brute is high attack and low
defence, a carapace the reverse, a swift one is middling in both and wears a
weapon harder for it."""

HEADER_SPOILS = """Generated by scripts/gen_monsters.py -- do not edit by hand.

§9.5.8 Tier 1 -- what comes off a monster. Two families of five: a plate/hide
line the smith and the armorer want, an ichor/organ line the consumable bench
wants. Biome-free, because they come off a thing that walked there rather than
out of the ground, and dropped by nothing else.

Combat feeds combat. Nothing here enters the mining economy, which is what makes
a whole new faucet safe under §2."""


def php_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


ts_str = php_str


def doc(o, header, prefix=' * '):
    o.write('/**\n')
    for line in header.split('\n'):
        o.write(f'{prefix}{line}\n'.rstrip() + '\n' if line else ' *\n')
    o.write(' */\n')


def pool(ring):
    """A ring fights its own tier and the one outside it."""
    tier = RINGS.index(ring) + 1
    return [m[0] for m in MONSTERS if m[2] in (tier, tier - 1)]


def drops(tier):
    """Grade of its tier, and rarely the one above. Tier 4 is where grade 5 lives."""
    return {
        'plate': PLATE[tier - 1][0],
        'ichor': ICHOR[tier - 1][0],
        'rare': PLATE[tier][0] if tier < 5 and tier < len(PLATE) else None,
    }


# ------------------------------------------------------------------- emitters

def emit_monsters_php():
    o = io.StringIO()
    o.write('<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Game;\n\n')
    doc(o, HEADER_MONSTERS)
    o.write('final class Monsters\n{\n')
    o.write('    /** §9.5.2 -- the roster. Flat attack and defence, never percentages. */\n')
    o.write('    public const ROSTER = [\n')
    for key, name, tier, profile, atk, dfn, wear, gold, desc in MONSTERS:
        d = drops(tier)
        rare = f"'{d['rare']}'" if d['rare'] else 'null'
        o.write(
            f"        '{key}' => ['name' => {php_str(name)}, 'tier' => {tier}, "
            f"'profile' => '{profile}', 'attack' => {atk}, 'defence' => {dfn}, "
            f"'wearBias' => {wear}, 'gold' => [{gold[0]}, {gold[1]}], "
            f"'plate' => '{d['plate']}', 'ichor' => '{d['ichor']}', 'rareSpoil' => {rare}, "
            f"'description' => {php_str(desc)}],\n"
        )
    o.write('    ];\n\n')
    o.write('    /**\n')
    o.write('     * §9.5.2 -- what stands on each ring. Two new, two carried in from\n')
    o.write('     * outside, and the outer ring has nothing outside it to carry.\n')
    o.write('     */\n')
    o.write('    public const BY_RING = [\n')
    for ring in RINGS:
        keys = ', '.join(f"'{k}'" for k in pool(ring))
        o.write(f"        '{ring}' => [{keys}],\n")
    o.write('    ];\n}\n')
    return o.getvalue()


def emit_monsters_ts():
    o = io.StringIO()
    doc(o, HEADER_MONSTERS)
    o.write("import type { Monster, Ring } from './types'\n\n")
    o.write('export const MONSTERS: Record<string, Monster> = {\n')
    for key, name, tier, profile, atk, dfn, wear, gold, desc in MONSTERS:
        d = drops(tier)
        rare = f"'{d['rare']}'" if d['rare'] else 'undefined'
        o.write(
            f"  {key}: {{ key: '{key}', name: {ts_str(name)}, tier: {tier}, "
            f"profile: '{profile}', attack: {atk}, defence: {dfn}, "
            f"wearBias: {wear}, gold: [{gold[0]}, {gold[1]}], "
            f"plate: '{d['plate']}', ichor: '{d['ichor']}', rareSpoil: {rare}, "
            f"description: {ts_str(desc)} }},\n"
        )
    o.write('}\n\n')
    o.write('export const MONSTERS_BY_RING: Record<Ring, string[]> = {\n')
    for ring in RINGS:
        keys = ', '.join(f"'{k}'" for k in pool(ring))
        o.write(f"  {ring}: [{keys}],\n")
    o.write('}\n')
    return o.getvalue()


def emit_spoils_php():
    o = io.StringIO()
    o.write('<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Game;\n\n')
    doc(o, HEADER_SPOILS)
    o.write('final class Spoils\n{\n')
    o.write('    /** §9.5.8 Tier 1 -- monster parts. Biome-free, dropped by nothing else. */\n')
    o.write('    public const STOCK = [\n')
    for family, rows, palette in (('plate', PLATE, 'pelt'), ('ichor', ICHOR, 'stone')):
        for key, name, grade, price, desc in rows:
            o.write(
                f"        '{key}' => ['name' => {php_str(name)}, 'tier' => 1, "
                f"'palette' => '{palette}', 'spoil' => '{family}', 'grade' => {grade}, "
                f"'npcPrice' => {price}, 'description' => {php_str(desc)}],\n"
            )
    o.write('    ];\n\n')
    o.write('    /** Grade -> the two things a monster of that tier gives up. */\n')
    o.write('    public const BY_GRADE = [\n')
    for i in range(len(PLATE)):
        o.write(f"        {i + 1} => ['plate' => '{PLATE[i][0]}', 'ichor' => '{ICHOR[i][0]}'],\n")
    o.write('    ];\n}\n')
    return o.getvalue()


def emit_spoils_ts():
    o = io.StringIO()
    doc(o, HEADER_SPOILS)
    o.write("import type { Material } from './types'\n\n")
    o.write('export const SPOILS: Material[] = [\n')
    for family, rows, palette in (('plate', PLATE, 'pelt'), ('ichor', ICHOR, 'stone')):
        for key, name, grade, price, desc in rows:
            o.write(
                f"  {{ key: '{key}', name: {ts_str(name)}, tier: 1, "
                f"palette: '{palette}', spoil: '{family}', grade: {grade}, "
                f"npcPrice: {price}, description: {ts_str(desc)} }},\n"
            )
    o.write(']\n\n')
    o.write('export const SPOILS_BY_GRADE: Record<number, { plate: string; ichor: string }> = {\n')
    for i in range(len(PLATE)):
        o.write(f"  {i + 1}: {{ plate: '{PLATE[i][0]}', ichor: '{ICHOR[i][0]}' }},\n")
    o.write('}\n')
    return o.getvalue()


if __name__ == '__main__':
    keys = [m[0] for m in MONSTERS]
    assert len(keys) == len(set(keys)), 'duplicate monster key'
    assert len(MONSTERS) == 8, 'the roster is eight'
    for tier in (1, 2, 3, 4):
        assert sum(1 for m in MONSTERS if m[2] == tier) == 2, f'tier {tier} is not two monsters'
    for ring in RINGS:
        assert len(pool(ring)) == (2 if ring == 'outer' else 4), f'{ring} pool is the wrong size'

    spoil_keys = [s[0] for s in PLATE + ICHOR]
    assert len(spoil_keys) == len(set(spoil_keys)), 'duplicate spoil key'
    assert len(spoil_keys) == 10, 'two families of five'
    for key, _, _, price, _ in PLATE + ICHOR:
        assert price > 1, f'{key} sells for scrap money'

    # §9.5.5 -- the pair is what decides a fight, so every tier has to sit clear
    # of the one outside it. Within a tier the split is free; the sum is not.
    by_tier = {t: [m[4] + m[5] for m in MONSTERS if m[2] == t] for t in (1, 2, 3, 4)}
    for t in (2, 3, 4):
        assert min(by_tier[t]) > max(by_tier[t - 1]), f'tier {t} is not harder than tier {t - 1}'

    open('app/Game/Monsters.php', 'w').write(emit_monsters_php())
    open('resources/js/game/monsters.ts', 'w').write(emit_monsters_ts())
    open('app/Game/Spoils.php', 'w').write(emit_spoils_php())
    open('resources/js/game/spoils.ts', 'w').write(emit_spoils_ts())
    print(f'{len(MONSTERS)} monsters, {len(spoil_keys)} spoils')
